/*
  File generated by Magnet rest2mobile 1.1 - Nov 14, 2017 10:57:15 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatidMtestid.model.beans;


/**
 * Generated from json example
 {
 "PatId" : "",
 "MtestId" : "",
 "MethodName" : ""
 }

 */

public class PostPatidMtestidRequest {


    @com.google.gson.annotations.SerializedName("MethodName")
    private String methodName;


    @com.google.gson.annotations.SerializedName("MtestId")
    private String mtestId;


    @com.google.gson.annotations.SerializedName("PatId")
    private String patId;

    public PostPatidMtestidRequest() {
    }

    public final String getMethodName() {
        return this.methodName;
    }

    public final void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    public final String getMtestId() {
        return this.mtestId;
    }

    public final void setMtestId(String mtestId) {
        this.mtestId = mtestId;
    }

    public final String getPatId() {
        return this.patId;
    }

    public final void setPatId(String patId) {
        this.patId = patId;
    }

    /**
     * Builder for PostPatidMtestidRequest
     **/
    public static class PostPatidMtestidRequestBuilder {
        private final PostPatidMtestidRequest toBuild = new PostPatidMtestidRequest();

        public PostPatidMtestidRequestBuilder() {
        }

        public final PostPatidMtestidRequest build() {
            return this.toBuild;
        }

        public final PostPatidMtestidRequest.PostPatidMtestidRequestBuilder methodName(String value) {
            this.toBuild.setMethodName(value);
            return this;
        }

        public final PostPatidMtestidRequest.PostPatidMtestidRequestBuilder mtestId(String value) {
            this.toBuild.setMtestId(value);
            return this;
        }

        public final PostPatidMtestidRequest.PostPatidMtestidRequestBuilder patId(String value) {
            this.toBuild.setPatId(value);
            return this;
        }
    }
}
