/*
  File generated by Magnet rest2mobile 1.1 - Nov 14, 2017 10:57:15 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatidMtestid.model.beans;


/**
 * Generated from json example
 {
 "PatId" : "",
 "MtestId" : "",
 "MethodName" : ""
 }

 */

public class PostPatidMtestidRequest {


    @com.google.gson.annotations.SerializedName("MethodName")
    private String methodName = null;


    @com.google.gson.annotations.SerializedName("MtestId")
    private String mtestId = null;


    @com.google.gson.annotations.SerializedName("PatId")
    private String patId = null;

    public PostPatidMtestidRequest() {
    }

    public final String getMethodName() {
        return methodName;
    }

    public final void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    public final String getMtestId() {
        return mtestId;
    }

    public final void setMtestId(String mtestId) {
        this.mtestId = mtestId;
    }

    public final String getPatId() {
        return patId;
    }

    public final void setPatId(String patId) {
        this.patId = patId;
    }

    /**
     * Builder for PostPatidMtestidRequest
     **/
    public static class PostPatidMtestidRequestBuilder {
        private final PostPatidMtestidRequest toBuild = new PostPatidMtestidRequest();

        public PostPatidMtestidRequestBuilder() {
        }

        public final PostPatidMtestidRequest build() {
            return toBuild;
        }

        public final PostPatidMtestidRequestBuilder methodName(String value) {
            toBuild.setMethodName(value);
            return this;
        }

        public final PostPatidMtestidRequestBuilder mtestId(String value) {
            toBuild.setMtestId(value);
            return this;
        }

        public final PostPatidMtestidRequestBuilder patId(String value) {
            toBuild.setPatId(value);
            return this;
        }
    }
}
