/*
  File generated by Magnet rest2mobile 1.1 - Nov 14, 2017 10:57:15 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatidMtestid.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatidMtestid.model.beans.PatidMtestidResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatidMtestid.model.beans.PostPatidMtestidRequest;

public interface PostPatidMtestid {

    /**
     * Generated from URL POST http://192.168.137.143:1234/importMasters/postPatidMtestid
     * POST importMasters/postPatidMtestid
     * @param body  style:PLAIN
     * @param listener
     * @return PatidMtestidResult
     */
    Call<PatidMtestidResult> postPatidMtestid(
            PostPatidMtestidRequest body,
            StateChangedListener listener
    );


}
