/*
  File generated by Magnet rest2mobile 1.1 - Nov 14, 2017 10:57:15 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatidMtestid.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatidMtestid.model.beans.PatidMtestidResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatidMtestid.model.beans.PostPatidMtestidRequest;

public class PostPatidMtestidFactory extends ControllerFactory<PostPatidMtestid> {
    public PostPatidMtestidFactory(MagnetMobileClient magnetClient) {
        super(PostPatidMtestid.class, PostPatidMtestidSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PostPatidMtestid
    public static class PostPatidMtestidSchemaFactory extends AbstractControllerSchemaFactory {
        private static PostPatidMtestidSchemaFactory __instance = null;

        private PostPatidMtestidSchemaFactory() {
        }

        static PostPatidMtestidSchemaFactory getInstance() {
            synchronized (PostPatidMtestidSchemaFactory.class) {
                if (null == __instance) {
                    __instance = new PostPatidMtestidSchemaFactory();
                }

                return __instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != schema) {
                    return;
                }

                schema = new RequestSchema();
                schema.setRootPath("");

                //controller schema for controller method postPatidMtestid
                JMethod method1 = addMethod("postPatidMtestid",
                        "importMastersSP/postPatidMtestid",
                        "POST",
                        PatidMtestidResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("body",
                        "PLAIN",
                        PostPatidMtestidRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
