/*
  File generated by Magnet rest2mobile 1.1 - Nov 14, 2017 10:57:15 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatidMtestid.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatidMtestid.model.beans.PatidMtestidResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatidMtestid.model.beans.PostPatidMtestidRequest;

public class PostPatidMtestidFactory extends ControllerFactory<PostPatidMtestid> {
    public PostPatidMtestidFactory(MagnetMobileClient magnetClient) {
        super(PostPatidMtestid.class, PostPatidMtestidFactory.PostPatidMtestidSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PostPatidMtestid
    public static class PostPatidMtestidSchemaFactory extends AbstractControllerSchemaFactory {
        private static PostPatidMtestidFactory.PostPatidMtestidSchemaFactory __instance;

        private PostPatidMtestidSchemaFactory() {
        }

        static PostPatidMtestidFactory.PostPatidMtestidSchemaFactory getInstance() {
            synchronized (PostPatidMtestidFactory.PostPatidMtestidSchemaFactory.class) {
                if (null == PostPatidMtestidFactory.PostPatidMtestidSchemaFactory.__instance) {
                    PostPatidMtestidFactory.PostPatidMtestidSchemaFactory.__instance = new PostPatidMtestidFactory.PostPatidMtestidSchemaFactory();
                }

                return PostPatidMtestidFactory.PostPatidMtestidSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method postPatidMtestid
                RequestSchema.JMethod method1 = this.addMethod("postPatidMtestid",
                        "importMastersSP/postPatidMtestid",
                        "POST",
                        PatidMtestidResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("body",
                        "PLAIN",
                        PostPatidMtestidRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
