/*
  File generated by Magnet rest2mobile 1.1 - Nov 14, 2017 10:42:38 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatId.model.beans;


/**
 * Generated from json example
 {
 "Results" : ""
 }

 */

public class PosPatIdResult {


    @com.google.gson.annotations.SerializedName("Results")
    private String results;

    public PosPatIdResult() {
    }

    public final String getResults() {
        return this.results;
    }

    public void setResults(String results) {
        this.results = results;
    }

    /**
     * Builder for PosPatIdResult
     **/
    public static class PosPatIdResultBuilder {
        private final PosPatIdResult toBuild = new PosPatIdResult();

        public PosPatIdResultBuilder() {
        }

        public final PosPatIdResult build() {
            return this.toBuild;
        }

        public final PosPatIdResult.PosPatIdResultBuilder results(String value) {
            this.toBuild.setResults(value);
            return this;
        }
    }
}
