/*
  File generated by Magnet rest2mobile 1.1 - Nov 14, 2017 10:42:38 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatId.model.beans;


/**
 * Generated from json example
 {
 "PatientId" : ""
 }

 */

public class PosPatIdRequest {


    @com.google.gson.annotations.SerializedName("PatientId")
    private String patientId;

    public PosPatIdRequest() {
    }

    public final String getPatientId() {
        return this.patientId;
    }

    public final void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    /**
     * Builder for PosPatIdRequest
     **/
    public static class PosPatIdRequestBuilder {
        private final PosPatIdRequest toBuild = new PosPatIdRequest();

        public PosPatIdRequestBuilder() {
        }

        public final PosPatIdRequest build() {
            return this.toBuild;
        }

        public final PosPatIdRequest.PosPatIdRequestBuilder patientId(String value) {
            this.toBuild.setPatientId(value);
            return this;
        }
    }
}
