/*
  File generated by Magnet rest2mobile 1.1 - 9 Feb, 2018 2:56:41 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.geAppMaster.controller.api;


import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.geAppMaster.model.beans.AppMasterResult;

public class AppMasterFactory extends ControllerFactory<AppMaster> {
    public AppMasterFactory(MagnetMobileClient magnetClient) {
        super(AppMaster.class, AppMasterSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller AppMaster
    public static class AppMasterSchemaFactory extends AbstractControllerSchemaFactory {
        private static AppMasterSchemaFactory __instance = null;

        private AppMasterSchemaFactory() {
        }

        static AppMasterSchemaFactory getInstance() {
            synchronized (AppMasterSchemaFactory.class) {
                if (null == __instance) {
                    __instance = new AppMasterSchemaFactory();
                }

                return __instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != schema) {
                    return;
                }

                schema = new RequestSchema();
                schema.setRootPath("");

                //controller schema for controller method getAppMaster
                JMethod method1 = addMethod("getAppMaster",
                        "data/getAppMaster",
                        "GET",
                        AppMasterResult.class,
                        null,
                        null,
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
            }
        }

    }

}
