/*
  File generated by Magnet rest2mobile 1.1 - 9 Feb, 2018 2:56:41 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.geAppMaster.controller.api;


import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.geAppMaster.model.beans.AppMasterResult;

public class AppMasterFactory extends ControllerFactory<AppMaster> {
    public AppMasterFactory(MagnetMobileClient magnetClient) {
        super(AppMaster.class, AppMasterFactory.AppMasterSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller AppMaster
    public static class AppMasterSchemaFactory extends AbstractControllerSchemaFactory {
        private static AppMasterFactory.AppMasterSchemaFactory __instance;

        private AppMasterSchemaFactory() {
        }

        static AppMasterFactory.AppMasterSchemaFactory getInstance() {
            synchronized (AppMasterFactory.AppMasterSchemaFactory.class) {
                if (null == AppMasterFactory.AppMasterSchemaFactory.__instance) {
                    AppMasterFactory.AppMasterSchemaFactory.__instance = new AppMasterFactory.AppMasterSchemaFactory();
                }

                return AppMasterFactory.AppMasterSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method getAppMaster
                RequestSchema.JMethod method1 = this.addMethod("getAppMaster",
                        "data/getAppMaster",
                        "GET",
                        AppMasterResult.class,
                        null,
                        null,
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
            }
        }

    }

}
