/*
  File generated by Magnet rest2mobile 1.1 - Dec 14, 2017 11:38:56 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.newPosPatIdDocIdMtestIdNew.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.importREST_Services.newPosPatIdDocIdMtestIdNew.beans.PosPatIdDocIdMtestIdRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.newPosPatIdDocIdMtestIdNew.beans.PosPatIdDocIdMtestIdResult;

public interface PosPatIdDocIdMtestIdNew {

    /**
     * Generated from URL POST http://192.168.137.143:1234/importMasters/postDoctorIdPatidMtestId
     * POST importMasters/postDoctorIdPatidMtestId
     * @param contentType (original name : Content-Type) style:HEADER
     * @param body  style:PLAIN
     * @param listener
     * @return PosPatIdDocIdMtestIdResult
     */
    Call<PosPatIdDocIdMtestIdResult> posPatIdDocIdMtestId(
            String contentType,
            PosPatIdDocIdMtestIdRequest body,
            StateChangedListener listener
    );


}
