/*
  File generated by Magnet rest2mobile 1.1 - Dec 14, 2017 11:38:56 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.newPosPatIdDocIdMtestIdNew.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.newPosPatIdDocIdMtestIdNew.beans.PosPatIdDocIdMtestIdRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.newPosPatIdDocIdMtestIdNew.beans.PosPatIdDocIdMtestIdResult;

public class PosPatIdDocIdMtestIdNewFactory extends ControllerFactory<PosPatIdDocIdMtestIdNew> {
    public PosPatIdDocIdMtestIdNewFactory(MagnetMobileClient magnetClient) {
        super(PosPatIdDocIdMtestIdNew.class, PosPatIdDocIdMtestIdNewSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PosPatIdDocIdMtestIdNew
    public static class PosPatIdDocIdMtestIdNewSchemaFactory extends AbstractControllerSchemaFactory {
        private static PosPatIdDocIdMtestIdNewSchemaFactory __instance = null;

        private PosPatIdDocIdMtestIdNewSchemaFactory() {
        }

        static PosPatIdDocIdMtestIdNewSchemaFactory getInstance() {
            synchronized (PosPatIdDocIdMtestIdNewSchemaFactory.class) {
                if (null == __instance) {
                    __instance = new PosPatIdDocIdMtestIdNewSchemaFactory();
                }

                return __instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != schema) {
                    return;
                }

                schema = new RequestSchema();
                schema.setRootPath("");

                //controller schema for controller method posPatIdDocIdMtestId
                JMethod method1 = addMethod("posPatIdDocIdMtestId",
                        "importMastersSP/postDoctorIdPatidMtestId",
                        "POST",
                        PosPatIdDocIdMtestIdResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("Content-Type",
                        "HEADER",
                        String.class,
                        null,
                        "",
                        true);
                method1.addParam("body",
                        "PLAIN",
                        PosPatIdDocIdMtestIdRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
