/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 1:21:26 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postIsUpdateMaxDocId.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postIsUpdateMaxDocId.model.beans.IsUpdateMaxDocIdResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postIsUpdateMaxDocId.model.beans.PostIsUpdateMaxDocIdRequest;

public class PostIsUpdateMaxDocIdFactory extends ControllerFactory<PostIsUpdateMaxDocId> {
    public PostIsUpdateMaxDocIdFactory(MagnetMobileClient magnetClient) {
        super(PostIsUpdateMaxDocId.class, PostIsUpdateMaxDocIdFactory.PostIsUpdateMaxDocIdSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PostIsUpdateMaxDocId
    public static class PostIsUpdateMaxDocIdSchemaFactory extends AbstractControllerSchemaFactory {
        private static PostIsUpdateMaxDocIdFactory.PostIsUpdateMaxDocIdSchemaFactory __instance;

        private PostIsUpdateMaxDocIdSchemaFactory() {
        }

        static PostIsUpdateMaxDocIdFactory.PostIsUpdateMaxDocIdSchemaFactory getInstance() {
            synchronized (PostIsUpdateMaxDocIdFactory.PostIsUpdateMaxDocIdSchemaFactory.class) {
                if (null == PostIsUpdateMaxDocIdFactory.PostIsUpdateMaxDocIdSchemaFactory.__instance) {
                    PostIsUpdateMaxDocIdFactory.PostIsUpdateMaxDocIdSchemaFactory.__instance = new PostIsUpdateMaxDocIdFactory.PostIsUpdateMaxDocIdSchemaFactory();
                }

                return PostIsUpdateMaxDocIdFactory.PostIsUpdateMaxDocIdSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method postIsUpdateMaxDocId
                RequestSchema.JMethod method1 = this.addMethod("postIsUpdateMaxDocId",
                        "importMastersSP/postDocIdIsUpdateMax",
                        "POST",
                        IsUpdateMaxDocIdResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("body",
                        "PLAIN",
                        PostIsUpdateMaxDocIdRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
