/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 1:21:26 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postIsUpdateMaxDocId.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postIsUpdateMaxDocId.model.beans.IsUpdateMaxDocIdResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postIsUpdateMaxDocId.model.beans.PostIsUpdateMaxDocIdRequest;

public class PostIsUpdateMaxDocIdFactory extends ControllerFactory<PostIsUpdateMaxDocId> {
    public PostIsUpdateMaxDocIdFactory(MagnetMobileClient magnetClient) {
        super(PostIsUpdateMaxDocId.class, PostIsUpdateMaxDocIdSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PostIsUpdateMaxDocId
    public static class PostIsUpdateMaxDocIdSchemaFactory extends AbstractControllerSchemaFactory {
        private static PostIsUpdateMaxDocIdSchemaFactory __instance = null;

        private PostIsUpdateMaxDocIdSchemaFactory() {
        }

        static PostIsUpdateMaxDocIdSchemaFactory getInstance() {
            synchronized (PostIsUpdateMaxDocIdSchemaFactory.class) {
                if (null == __instance) {
                    __instance = new PostIsUpdateMaxDocIdSchemaFactory();
                }

                return __instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != schema) {
                    return;
                }

                schema = new RequestSchema();
                schema.setRootPath("");

                //controller schema for controller method postIsUpdateMaxDocId
                JMethod method1 = addMethod("postIsUpdateMaxDocId",
                        "importMastersSP/postDocIdIsUpdateMax",
                        "POST",
                        IsUpdateMaxDocIdResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("body",
                        "PLAIN",
                        PostIsUpdateMaxDocIdRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
