/*
  File generated by Magnet rest2mobile 1.1 - Nov 2, 2017 12:56:35 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.insertTable.model.beans;

import java.util.List;

/**
 * Generated from json example
 {
 "ServerID" : [ {
 "Id" : 334
 }, {
 "Id" : 335
 } ],
 "LocalID" : [ "5", "54" ]
 }

 */

public class TableDataResult {


    @com.google.gson.annotations.SerializedName("LocalID")
    private List<String> localID;


    @com.google.gson.annotations.SerializedName("ServerID")
    private List<ServerID> serverID;

    public TableDataResult() {
    }

    public final List<String> getLocalID() {
        return this.localID;
    }

    public final List<ServerID> getServerID() {
        return this.serverID;
    }

    public void setLocalID(List<String> localID) {
        this.localID = localID;
    }

    public void setServerID(List<ServerID> serverID) {
        this.serverID = serverID;
    }

    /**
     * Builder for TableDataResult
     **/
    public static class TableDataResultBuilder {
        private final TableDataResult toBuild = new TableDataResult();

        public TableDataResultBuilder() {
        }

        public final TableDataResult build() {
            return this.toBuild;
        }

        public final TableDataResult.TableDataResultBuilder localID(List<String> value) {
            this.toBuild.setLocalID(value);
            return this;
        }

        public final TableDataResult.TableDataResultBuilder serverID(List<ServerID> value) {
            this.toBuild.setServerID(value);
            return this;
        }
    }
}
