/*
  File generated by Magnet rest2mobile 1.1 - Jan 24, 2018 12:21:20 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.getUpdateDB.model.beans;


/**
 * Generated from json example
 {
 "Docid" : "DOCID/2017/05/81",
 "imei" : "",
 "mac" : "0"
 }

 */

public class GetUpdateDBRequest {


    @com.google.gson.annotations.SerializedName("Docid")
    private String docid;


    private String imei;


    private String mac;

    public GetUpdateDBRequest() {
    }

    public final String getDocid() {
        return this.docid;
    }

    public final void setDocid(String docid) {
        this.docid = docid;
    }

    public final String getImei() {
        return this.imei;
    }

    public final void setImei(String imei) {
        this.imei = imei;
    }

    public final String getMac() {
        return this.mac;
    }

    public final void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * Builder for GetUpdateDBRequest
     **/
    public static class GetUpdateDBRequestBuilder {
        private final GetUpdateDBRequest toBuild = new GetUpdateDBRequest();

        public GetUpdateDBRequestBuilder() {
        }

        public final GetUpdateDBRequest build() {
            return this.toBuild;
        }

        public final GetUpdateDBRequest.GetUpdateDBRequestBuilder docid(String value) {
            this.toBuild.setDocid(value);
            return this;
        }

        public final GetUpdateDBRequest.GetUpdateDBRequestBuilder imei(String value) {
            this.toBuild.setImei(value);
            return this;
        }

        public final GetUpdateDBRequest.GetUpdateDBRequestBuilder mac(String value) {
            this.toBuild.setMac(value);
            return this;
        }
    }
}
