/*
  File generated by Magnet rest2mobile 1.1 - Jan 24, 2018 12:21:20 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.getUpdateDB.model.beans;


/**
 * Generated from json example
 {
 "Results" : ""
 }

 */

public class UpdateDBResult {


    @com.google.gson.annotations.SerializedName("Results")
    private String results = null;

    public UpdateDBResult() {
    }

    public final String getResults() {
        return results;
    }

    public void setResults(String results) {
        this.results = results;
    }

    /**
     * Builder for UpdateDBResult
     **/
    public static class UpdateDBResultBuilder {
        private final UpdateDBResult toBuild = new UpdateDBResult();

        public UpdateDBResultBuilder() {
        }

        public final UpdateDBResult build() {
            return toBuild;
        }

        public final UpdateDBResultBuilder results(String value) {
            toBuild.setResults(value);
            return this;
        }
    }
}
