/*
  File generated by Magnet rest2mobile 1.1 - 8 Feb, 2018 1:39:17 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.getDoctorDetails.model.beans;


/**
 * Generated from json example
 {
 "docid" : "DOCID/2018/02/1"
 }

 */

public class PostDoctorIdRequest {


    private String docid;

    public PostDoctorIdRequest() {
    }

    public final String getDocid() {
        return this.docid;
    }

    public final void setDocid(String docid) {
        this.docid = docid;
    }

    /**
     * Builder for PostDoctorIdRequest
     **/
    public static class PostDoctorIdRequestBuilder {
        private final PostDoctorIdRequest toBuild = new PostDoctorIdRequest();

        public PostDoctorIdRequestBuilder() {
        }

        public final PostDoctorIdRequest build() {
            return this.toBuild;
        }

        public final PostDoctorIdRequest.PostDoctorIdRequestBuilder docid(String value) {
            this.toBuild.setDocid(value);
            return this;
        }
    }
}
