/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 6:36:07 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postImmunizationInfo.model.beans;


/**
 * Generated from json example
 {
 "PatId" : "",
 "DocId" : ""
 }

 */

public class PosImmunizationInfoRequest {


    @com.google.gson.annotations.SerializedName("DocId")
    private String docId;


    @com.google.gson.annotations.SerializedName("PatId")
    private String patId;

    public PosImmunizationInfoRequest() {
    }

    public final String getDocId() {
        return this.docId;
    }

    public final void setDocId(String docId) {
        this.docId = docId;
    }

    public final String getPatId() {
        return this.patId;
    }

    public final void setPatId(String patId) {
        this.patId = patId;
    }

    /**
     * Builder for PosImmunizationInfoRequest
     **/
    public static class PosImmunizationInfoRequestBuilder {
        private final PosImmunizationInfoRequest toBuild = new PosImmunizationInfoRequest();

        public PosImmunizationInfoRequestBuilder() {
        }

        public final PosImmunizationInfoRequest build() {
            return this.toBuild;
        }

        public final PosImmunizationInfoRequest.PosImmunizationInfoRequestBuilder docId(String value) {
            this.toBuild.setDocId(value);
            return this;
        }

        public final PosImmunizationInfoRequest.PosImmunizationInfoRequestBuilder patId(String value) {
            this.toBuild.setPatId(value);
            return this;
        }
    }
}
