/*
  File generated by Magnet rest2mobile 1.1 - 8 Feb, 2018 12:31:43 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.checkCredential.model.beans;


/**
 * Generated from json example
 {
 "Username" : "hari",
 "Password" : "MTIz",
 "imei" : "imei",
 "mac" : "mac"
 }

 */

public class PostUsernamePasswordRequest {


    private String imei = null;


    private String mac = null;


    @com.google.gson.annotations.SerializedName("Password")
    private String password = null;


    @com.google.gson.annotations.SerializedName("Username")
    private String username = null;

    public PostUsernamePasswordRequest() {
    }

    public final String getImei() {
        return imei;
    }

    public final void setImei(String imei) {
        this.imei = imei;
    }

    public final String getMac() {
        return mac;
    }

    public final void setMac(String mac) {
        this.mac = mac;
    }

    public final String getPassword() {
        return password;
    }

    public final void setPassword(String password) {
        this.password = password;
    }

    public final String getUsername() {
        return username;
    }

    public final void setUsername(String username) {
        this.username = username;
    }

    /**
     * Builder for PostUsernamePasswordRequest
     **/
    public static class PostUsernamePasswordRequestBuilder {
        private final PostUsernamePasswordRequest toBuild = new PostUsernamePasswordRequest();

        public PostUsernamePasswordRequestBuilder() {
        }

        public final PostUsernamePasswordRequest build() {
            return toBuild;
        }

        public final PostUsernamePasswordRequestBuilder imei(String value) {
            toBuild.setImei(value);
            return this;
        }

        public final PostUsernamePasswordRequestBuilder mac(String value) {
            toBuild.setMac(value);
            return this;
        }

        public final PostUsernamePasswordRequestBuilder password(String value) {
            toBuild.setPassword(value);
            return this;
        }

        public final PostUsernamePasswordRequestBuilder username(String value) {
            toBuild.setUsername(value);
            return this;
        }
    }
}
