/*
  File generated by Magnet rest2mobile 1.1 - 8 Feb, 2018 12:31:43 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.checkCredential.model.beans;


/**
 * Generated from json example
 {
 "Results" : ""
 }

 */

public class UsernamePasswordResult {


    @com.google.gson.annotations.SerializedName("Results")
    private String results;

    public UsernamePasswordResult() {
    }

    public final String getResults() {
        return this.results;
    }

    public void setResults(String results) {
        this.results = results;
    }

    /**
     * Builder for UsernamePasswordResult
     **/
    public static class UsernamePasswordResultBuilder {
        private final UsernamePasswordResult toBuild = new UsernamePasswordResult();

        public UsernamePasswordResultBuilder() {
        }

        public final UsernamePasswordResult build() {
            return this.toBuild;
        }

        public final UsernamePasswordResult.UsernamePasswordResultBuilder results(String value) {
            this.toBuild.setResults(value);
            return this;
        }
    }
}
