/*
  File generated by Magnet rest2mobile 1.1 - 9 Mar, 2018 12:44:19 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.generatePDFNode.model.beans;


/**
 * Generated from json example
 {
 "JsonValue" : {
 "PATIENTID" : "",
 "INVESTIGATIONID" : "",
 "MEDICINEID" : "",
 "SYMPTOMS" : "",
 "DIAGNOSIS" : "",
 "PATIENTNAME" : "",
 "AGE" : "",
 "GENDER" : "",
 "DOCTORNAME" : "",
 "DOCTORID" : "",
 "DATETIME" : "",
 "NEXTVISITDATE" : "",
 "DIAGNOSISID" : ""
 }
 }

 */

public class GetPDFNodeJsRequest {


    @com.google.gson.annotations.SerializedName("JsonValue")
    private JsonValue jsonValue;

    public GetPDFNodeJsRequest() {
    }

    public final JsonValue getJsonValue() {
        return this.jsonValue;
    }

    public final void setJsonValue(JsonValue jsonValue) {
        this.jsonValue = jsonValue;
    }

    /**
     * Builder for GetPDFNodeJsRequest
     **/
    public static class GetPDFNodeJsRequestBuilder {
        private final GetPDFNodeJsRequest toBuild = new GetPDFNodeJsRequest();

        public GetPDFNodeJsRequestBuilder() {
        }

        public final GetPDFNodeJsRequest build() {
            return this.toBuild;
        }

        public final GetPDFNodeJsRequest.GetPDFNodeJsRequestBuilder jsonValue(JsonValue value) {
            this.toBuild.setJsonValue(value);
            return this;
        }
    }
}
