/*
  File generated by Magnet rest2mobile 1.1 - 9 Mar, 2018 12:44:19 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.generatePDFNode.model.beans;


/**
 * Generated from json example
 {
 "PATIENTID" : "",
 "INVESTIGATIONID" : "",
 "MEDICINEID" : "",
 "SYMPTOMS" : "",
 "DIAGNOSIS" : "",
 "PATIENTNAME" : "",
 "AGE" : "",
 "GENDER" : "",
 "DOCTORNAME" : "",
 "DOCTORID" : "",
 "DATETIME" : "",
 "NEXTVISITDATE" : "",
 "DIAGNOSISID" : ""
 }

 */

public class JsonValue {


    @com.google.gson.annotations.SerializedName("AGE")
    private String aGE;


    @com.google.gson.annotations.SerializedName("DATETIME")
    private String dATETIME;


    @com.google.gson.annotations.SerializedName("DIAGNOSIS")
    private String dIAGNOSIS;


    @com.google.gson.annotations.SerializedName("DIAGNOSISID")
    private String dIAGNOSISID;


    @com.google.gson.annotations.SerializedName("DOCTORID")
    private String dOCTORID;


    @com.google.gson.annotations.SerializedName("DOCTORSPEC")
    private String dOCTORSPEC;

    @com.google.gson.annotations.SerializedName("DOCTORNAME")
    private String dOCTORNAME;

    @com.google.gson.annotations.SerializedName("HOSPITALNAME")
    private String hOSPITALNAME;


    @com.google.gson.annotations.SerializedName("GENDER")
    private String gENDER;


    @com.google.gson.annotations.SerializedName("INVESTIGATIONID")
    private String iNVESTIGATIONID;


    @com.google.gson.annotations.SerializedName("MEDICINEID")
    private String mEDICINEID;


    @com.google.gson.annotations.SerializedName("NEXTVISITDATE")
    private String nEXTVISITDATE;


    @com.google.gson.annotations.SerializedName("PATIENTID")
    private String pATIENTID;


    @com.google.gson.annotations.SerializedName("PATIENTNAME")
    private String pATIENTNAME;


    @com.google.gson.annotations.SerializedName("SYMPTOMS")
    private String sYMPTOMS;

    public JsonValue() {
    }

    public final String getAGE() {
        return this.getaGE();
    }

    public final String getDATETIME() {
        return this.getdATETIME();
    }

    public final String getDIAGNOSIS() {
        return this.getdIAGNOSIS();
    }

    public final String getDIAGNOSISID() {
        return this.getdIAGNOSISID();
    }

    public final String getDOCTORID() {
        return this.getdOCTORID();
    }

    public final String getDOCTORNAME() {
        return this.getdOCTORNAME();
    }

    public final String getGENDER() {
        return this.getgENDER();
    }

    public final String getINVESTIGATIONID() {
        return this.getiNVESTIGATIONID();
    }

    public final String getMEDICINEID() {
        return this.getmEDICINEID();
    }

    public final String getNEXTVISITDATE() {
        return this.getnEXTVISITDATE();
    }

    public final String getPATIENTID() {
        return this.getpATIENTID();
    }

    public final String getPATIENTNAME() {
        return this.getpATIENTNAME();
    }

    public final String getSYMPTOMS() {
        return this.getsYMPTOMS();
    }


    public final void setaGE(String aGE) {
        this.aGE = aGE;
    }

    public final void setdATETIME(String dATETIME) {
        this.dATETIME = dATETIME;
    }

    public final void setdIAGNOSIS(String dIAGNOSIS) {
        this.dIAGNOSIS = dIAGNOSIS;
    }

    public final void setdIAGNOSISID(String dIAGNOSISID) {
        this.dIAGNOSISID = dIAGNOSISID;
    }

    public final void setdOCTORID(String dOCTORID) {
        this.dOCTORID = dOCTORID;
    }

    public final void setdOCTORNAME(String dOCTORNAME) {
        this.dOCTORNAME = dOCTORNAME;
    }

    public final void setgENDER(String gENDER) {
        this.gENDER = gENDER;
    }

    public final void setiNVESTIGATIONID(String iNVESTIGATIONID) {
        this.iNVESTIGATIONID = iNVESTIGATIONID;
    }

    public final void setmEDICINEID(String mEDICINEID) {
        this.mEDICINEID = mEDICINEID;
    }

    public final void setnEXTVISITDATE(String nEXTVISITDATE) {
        this.nEXTVISITDATE = nEXTVISITDATE;
    }

    public final void setpATIENTID(String pATIENTID) {
        this.pATIENTID = pATIENTID;
    }

    public final void setpATIENTNAME(String pATIENTNAME) {
        this.pATIENTNAME = pATIENTNAME;
    }

    public final void setsYMPTOMS(String sYMPTOMS) {
        this.sYMPTOMS = sYMPTOMS;
    }

    public final String getdOCTORSPEC() {
        return this.dOCTORSPEC;
    }

    public final void setdOCTORSPEC(String dOCTORSPEC) {
        this.dOCTORSPEC = dOCTORSPEC;
    }

    public final String gethOSPITALNAME() {
        return this.hOSPITALNAME;
    }

    public final void sethOSPITALNAME(String hOSPITALNAME) {
        this.hOSPITALNAME = hOSPITALNAME;
    }

    public String getaGE() {
        return this.aGE;
    }

    public String getdATETIME() {
        return this.dATETIME;
    }

    public String getdIAGNOSIS() {
        return this.dIAGNOSIS;
    }

    public String getdIAGNOSISID() {
        return this.dIAGNOSISID;
    }

    public String getdOCTORID() {
        return this.dOCTORID;
    }

    public String getdOCTORNAME() {
        return this.dOCTORNAME;
    }

    public String getgENDER() {
        return this.gENDER;
    }

    public String getiNVESTIGATIONID() {
        return this.iNVESTIGATIONID;
    }

    public String getmEDICINEID() {
        return this.mEDICINEID;
    }

    public String getnEXTVISITDATE() {
        return this.nEXTVISITDATE;
    }

    public String getpATIENTID() {
        return this.pATIENTID;
    }

    public String getpATIENTNAME() {
        return this.pATIENTNAME;
    }

    public String getsYMPTOMS() {
        return this.sYMPTOMS;
    }

    /**
     * Builder for JsonValue
     **/
    public static class JsonValueBuilder {
        private final JsonValue toBuild = new JsonValue();

        public JsonValueBuilder() {
        }

        public final JsonValue build() {
            return this.toBuild;
        }

        public final JsonValue.JsonValueBuilder aGE(String value) {
            this.toBuild.setaGE(value);
            return this;
        }

        public final JsonValue.JsonValueBuilder dATETIME(String value) {
            this.toBuild.setdATETIME(value);
            return this;
        }

        public final JsonValue.JsonValueBuilder dIAGNOSIS(String value) {
            this.toBuild.setdIAGNOSIS(value);
            return this;
        }

        public final JsonValue.JsonValueBuilder dIAGNOSISID(String value) {
            this.toBuild.setdIAGNOSISID(value);
            return this;
        }

        public final JsonValue.JsonValueBuilder dOCTORID(String value) {
            this.toBuild.setdOCTORID(value);
            return this;
        }

        public final JsonValue.JsonValueBuilder dOCTORNAME(String value) {
            this.toBuild.setdOCTORNAME(value);
            return this;
        }

        public final JsonValue.JsonValueBuilder gENDER(String value) {
            this.toBuild.setgENDER(value);
            return this;
        }

        public final JsonValue.JsonValueBuilder iNVESTIGATIONID(String value) {
            this.toBuild.setiNVESTIGATIONID(value);
            return this;
        }

        public final JsonValue.JsonValueBuilder mEDICINEID(String value) {
            this.toBuild.setmEDICINEID(value);
            return this;
        }

        public final JsonValue.JsonValueBuilder nEXTVISITDATE(String value) {
            this.toBuild.setnEXTVISITDATE(value);
            return this;
        }

        public final JsonValue.JsonValueBuilder pATIENTID(String value) {
            this.toBuild.setpATIENTID(value);
            return this;
        }

        public final JsonValue.JsonValueBuilder pATIENTNAME(String value) {
            this.toBuild.setpATIENTNAME(value);
            return this;
        }

        public final JsonValue.JsonValueBuilder sYMPTOMS(String value) {
            this.toBuild.setsYMPTOMS(value);
            return this;
        }
    }
}
