/*
  File generated by Magnet rest2mobile 1.1 - 9 Mar, 2018 12:44:19 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.generatePDFNode.model.beans;


/**
 * Generated from json example
 {
 "PATIENTID" : "",
 "INVESTIGATIONID" : "",
 "MEDICINEID" : "",
 "SYMPTOMS" : "",
 "DIAGNOSIS" : "",
 "PATIENTNAME" : "",
 "AGE" : "",
 "GENDER" : "",
 "DOCTORNAME" : "",
 "DOCTORID" : "",
 "DATETIME" : "",
 "NEXTVISITDATE" : "",
 "DIAGNOSISID" : ""
 }

 */

public class JsonValue {


    @com.google.gson.annotations.SerializedName("AGE")
    private String aGE = null;


    @com.google.gson.annotations.SerializedName("DATETIME")
    private String dATETIME = null;


    @com.google.gson.annotations.SerializedName("DIAGNOSIS")
    private String dIAGNOSIS = null;


    @com.google.gson.annotations.SerializedName("DIAGNOSISID")
    private String dIAGNOSISID = null;


    @com.google.gson.annotations.SerializedName("DOCTORID")
    private String dOCTORID = null;


    @com.google.gson.annotations.SerializedName("DOCTORSPEC")
    private String dOCTORSPEC = null;

    @com.google.gson.annotations.SerializedName("DOCTORNAME")
    private String dOCTORNAME = null;

    @com.google.gson.annotations.SerializedName("HOSPITALNAME")
    private String hOSPITALNAME = null;


    @com.google.gson.annotations.SerializedName("GENDER")
    private String gENDER = null;


    @com.google.gson.annotations.SerializedName("INVESTIGATIONID")
    private String iNVESTIGATIONID = null;


    @com.google.gson.annotations.SerializedName("MEDICINEID")
    private String mEDICINEID = null;


    @com.google.gson.annotations.SerializedName("NEXTVISITDATE")
    private String nEXTVISITDATE = null;


    @com.google.gson.annotations.SerializedName("PATIENTID")
    private String pATIENTID = null;


    @com.google.gson.annotations.SerializedName("PATIENTNAME")
    private String pATIENTNAME = null;


    @com.google.gson.annotations.SerializedName("SYMPTOMS")
    private String sYMPTOMS = null;

    public JsonValue() {
    }

    public final String getAGE() {
        return getaGE();
    }

    public final String getDATETIME() {
        return getdATETIME();
    }

    public final String getDIAGNOSIS() {
        return getdIAGNOSIS();
    }

    public final String getDIAGNOSISID() {
        return getdIAGNOSISID();
    }

    public final String getDOCTORID() {
        return getdOCTORID();
    }

    public final String getDOCTORNAME() {
        return getdOCTORNAME();
    }

    public final String getGENDER() {
        return getgENDER();
    }

    public final String getINVESTIGATIONID() {
        return getiNVESTIGATIONID();
    }

    public final String getMEDICINEID() {
        return getmEDICINEID();
    }

    public final String getNEXTVISITDATE() {
        return getnEXTVISITDATE();
    }

    public final String getPATIENTID() {
        return getpATIENTID();
    }

    public final String getPATIENTNAME() {
        return getpATIENTNAME();
    }

    public final String getSYMPTOMS() {
        return getsYMPTOMS();
    }


    public final void setaGE(String aGE) {
        this.aGE = aGE;
    }

    public final void setdATETIME(String dATETIME) {
        this.dATETIME = dATETIME;
    }

    public final void setdIAGNOSIS(String dIAGNOSIS) {
        this.dIAGNOSIS = dIAGNOSIS;
    }

    public final void setdIAGNOSISID(String dIAGNOSISID) {
        this.dIAGNOSISID = dIAGNOSISID;
    }

    public final void setdOCTORID(String dOCTORID) {
        this.dOCTORID = dOCTORID;
    }

    public final void setdOCTORNAME(String dOCTORNAME) {
        this.dOCTORNAME = dOCTORNAME;
    }

    public final void setgENDER(String gENDER) {
        this.gENDER = gENDER;
    }

    public final void setiNVESTIGATIONID(String iNVESTIGATIONID) {
        this.iNVESTIGATIONID = iNVESTIGATIONID;
    }

    public final void setmEDICINEID(String mEDICINEID) {
        this.mEDICINEID = mEDICINEID;
    }

    public final void setnEXTVISITDATE(String nEXTVISITDATE) {
        this.nEXTVISITDATE = nEXTVISITDATE;
    }

    public final void setpATIENTID(String pATIENTID) {
        this.pATIENTID = pATIENTID;
    }

    public final void setpATIENTNAME(String pATIENTNAME) {
        this.pATIENTNAME = pATIENTNAME;
    }

    public final void setsYMPTOMS(String sYMPTOMS) {
        this.sYMPTOMS = sYMPTOMS;
    }

    public final String getdOCTORSPEC() {
        return dOCTORSPEC;
    }

    public final void setdOCTORSPEC(String dOCTORSPEC) {
        this.dOCTORSPEC = dOCTORSPEC;
    }

    public final String gethOSPITALNAME() {
        return hOSPITALNAME;
    }

    public final void sethOSPITALNAME(String hOSPITALNAME) {
        this.hOSPITALNAME = hOSPITALNAME;
    }

    public String getaGE() {
        return aGE;
    }

    public String getdATETIME() {
        return dATETIME;
    }

    public String getdIAGNOSIS() {
        return dIAGNOSIS;
    }

    public String getdIAGNOSISID() {
        return dIAGNOSISID;
    }

    public String getdOCTORID() {
        return dOCTORID;
    }

    public String getdOCTORNAME() {
        return dOCTORNAME;
    }

    public String getgENDER() {
        return gENDER;
    }

    public String getiNVESTIGATIONID() {
        return iNVESTIGATIONID;
    }

    public String getmEDICINEID() {
        return mEDICINEID;
    }

    public String getnEXTVISITDATE() {
        return nEXTVISITDATE;
    }

    public String getpATIENTID() {
        return pATIENTID;
    }

    public String getpATIENTNAME() {
        return pATIENTNAME;
    }

    public String getsYMPTOMS() {
        return sYMPTOMS;
    }

    /**
     * Builder for JsonValue
     **/
    public static class JsonValueBuilder {
        private final JsonValue toBuild = new JsonValue();

        public JsonValueBuilder() {
        }

        public final JsonValue build() {
            return toBuild;
        }

        public final JsonValueBuilder aGE(String value) {
            toBuild.setaGE(value);
            return this;
        }

        public final JsonValueBuilder dATETIME(String value) {
            toBuild.setdATETIME(value);
            return this;
        }

        public final JsonValueBuilder dIAGNOSIS(String value) {
            toBuild.setdIAGNOSIS(value);
            return this;
        }

        public final JsonValueBuilder dIAGNOSISID(String value) {
            toBuild.setdIAGNOSISID(value);
            return this;
        }

        public final JsonValueBuilder dOCTORID(String value) {
            toBuild.setdOCTORID(value);
            return this;
        }

        public final JsonValueBuilder dOCTORNAME(String value) {
            toBuild.setdOCTORNAME(value);
            return this;
        }

        public final JsonValueBuilder gENDER(String value) {
            toBuild.setgENDER(value);
            return this;
        }

        public final JsonValueBuilder iNVESTIGATIONID(String value) {
            toBuild.setiNVESTIGATIONID(value);
            return this;
        }

        public final JsonValueBuilder mEDICINEID(String value) {
            toBuild.setmEDICINEID(value);
            return this;
        }

        public final JsonValueBuilder nEXTVISITDATE(String value) {
            toBuild.setnEXTVISITDATE(value);
            return this;
        }

        public final JsonValueBuilder pATIENTID(String value) {
            toBuild.setpATIENTID(value);
            return this;
        }

        public final JsonValueBuilder pATIENTNAME(String value) {
            toBuild.setpATIENTNAME(value);
            return this;
        }

        public final JsonValueBuilder sYMPTOMS(String value) {
            toBuild.setsYMPTOMS(value);
            return this;
        }
    }
}
