/*
  File generated by Magnet rest2mobile 1.1 - 9 Mar, 2018 12:44:19 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.generatePDFNode.model.beans;


/**
 * Generated from json example
 {
 "Result" : "PDF",
 "URL" : "PDFURL"
 }

 */

public class PDFNodeJsResult {


    @com.google.gson.annotations.SerializedName("Result")
    private String result;


    @com.google.gson.annotations.SerializedName("URL")
    private String uRL;

    public PDFNodeJsResult() {
    }

    public final String getResult() {
        return this.result;
    }

    public final String getURL() {
        return this.getuRL();
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String getuRL() {
        return this.uRL;
    }

    public void setuRL(String uRL) {
        this.uRL = uRL;
    }


    /**
     * Builder for PDFNodeJsResult
     **/
    public static class PDFNodeJsResultBuilder {
        private final PDFNodeJsResult toBuild = new PDFNodeJsResult();

        public PDFNodeJsResultBuilder() {
        }

        public final PDFNodeJsResult build() {
            return this.toBuild;
        }

        public final PDFNodeJsResult.PDFNodeJsResultBuilder result(String value) {
            this.toBuild.setResult(value);
            return this;
        }

        public final PDFNodeJsResult.PDFNodeJsResultBuilder uRL(String value) {
            this.toBuild.setuRL(value);
            return this;
        }
    }
}
