/*
  File generated by Magnet rest2mobile 1.1 - Nov 11, 2017 5:03:19 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.getPatientMapping.model.beans;


/**
 * Generated from json example
 {
 "IsUpdateMax" : "0",
 "HID" : "3"
 }

 */

public class GetPatientMappingRequest {


    @com.google.gson.annotations.SerializedName("HID")
    private String hID;


    @com.google.gson.annotations.SerializedName("IsUpdateMax")
    private String isUpdateMax;

    public GetPatientMappingRequest() {
    }

    public final String getHID() {
        return this.gethID();
    }

    public final String getIsUpdateMax() {
        return this.isUpdateMax;
    }

    public final void setIsUpdateMax(String isUpdateMax) {
        this.isUpdateMax = isUpdateMax;
    }

    public final void sethID(String hID) {
        this.hID = hID;
    }

    public String gethID() {
        return this.hID;
    }

    /**
     * Builder for GetPatientMappingRequest
     **/
    public static class GetPatientMappingRequestBuilder {
        private final GetPatientMappingRequest toBuild = new GetPatientMappingRequest();

        public GetPatientMappingRequestBuilder() {
        }

        public final GetPatientMappingRequest build() {
            return this.toBuild;
        }

        public final GetPatientMappingRequest.GetPatientMappingRequestBuilder hID(String value) {
            this.toBuild.sethID(value);
            return this;
        }

        public final GetPatientMappingRequest.GetPatientMappingRequestBuilder isUpdateMax(String value) {
            this.toBuild.setIsUpdateMax(value);
            return this;
        }
    }
}
