/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 1:42:33 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatientIdList.model.beans;


/**
 * Generated from json example
 {
 "Results" : ""
 }

 */

public class PatientIdListResult {


    @com.google.gson.annotations.SerializedName("Results")
    private String results;

    public PatientIdListResult() {
    }

    public final String getResults() {
        return this.results;
    }

    public void setResults(String results) {
        this.results = results;
    }

    /**
     * Builder for PatientIdListResult
     **/
    public static class PatientIdListResultBuilder {
        private final PatientIdListResult toBuild = new PatientIdListResult();

        public PatientIdListResultBuilder() {
        }

        public final PatientIdListResult build() {
            return this.toBuild;
        }

        public final PatientIdListResult.PatientIdListResultBuilder results(String value) {
            this.toBuild.setResults(value);
            return this;
        }
    }
}
