/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 1:42:33 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatientIdList.model.beans;


/**
 * Generated from json example
 {
 "PatientList" : "",
 "MethodName" : "MethodName"
 }

 */

public class PostPatientIdListRequest {


    @com.google.gson.annotations.SerializedName("MethodName")
    private String methodName = null;


    @com.google.gson.annotations.SerializedName("PatientList")
    private String patientList = null;

    public PostPatientIdListRequest() {
    }

    public final String getMethodName() {
        return methodName;
    }

    public final void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    public final String getPatientList() {
        return patientList;
    }

    public final void setPatientList(String patientList) {
        this.patientList = patientList;
    }

    /**
     * Builder for PostPatientIdListRequest
     **/
    public static class PostPatientIdListRequestBuilder {
        private final PostPatientIdListRequest toBuild = new PostPatientIdListRequest();

        public PostPatientIdListRequestBuilder() {
        }

        public final PostPatientIdListRequest build() {
            return toBuild;
        }

        public final PostPatientIdListRequestBuilder methodName(String value) {
            toBuild.setMethodName(value);
            return this;
        }

        public final PostPatientIdListRequestBuilder patientList(String value) {
            toBuild.setPatientList(value);
            return this;
        }
    }
}
