/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 1:21:26 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postIsUpdateMaxDocId.model.beans;


/**
 * Generated from json example
 {
 "Results" : ""
 }

 */

public class IsUpdateMaxDocIdResult {


    @com.google.gson.annotations.SerializedName("Results")
    private String results = null;

    public IsUpdateMaxDocIdResult() {
    }

    public final String getResults() {
        return results;
    }

    public void setResults(String results) {
        this.results = results;
    }

    /**
     * Builder for IsUpdateMaxDocIdResult
     **/
    public static class IsUpdateMaxDocIdResultBuilder {
        private final IsUpdateMaxDocIdResult toBuild = new IsUpdateMaxDocIdResult();

        public IsUpdateMaxDocIdResultBuilder() {
        }

        public final IsUpdateMaxDocIdResult build() {
            return toBuild;
        }

        public final IsUpdateMaxDocIdResultBuilder results(String value) {
            toBuild.setResults(value);
            return this;
        }
    }
}
