/*
  File generated by Magnet rest2mobile 1.1 - 27 Mar, 2018 5:10:19 PM
  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.exportCaseNotes.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Arrays;
import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.exportCaseNotes.model.beans.ExportCaseNotesRequest;
import kdmc_kumar.Webservices_NodeJSON.exportCaseNotes.model.beans.ExportCaseNotesResult;


public class ExportCaseNotesFactory extends ControllerFactory<ExportCaseNotes> {
  public ExportCaseNotesFactory(MagnetMobileClient magnetClient) {
    super(ExportCaseNotes.class, ExportCaseNotesFactory.ExportCaseNotesSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller ExportCaseNotes
  public static class ExportCaseNotesSchemaFactory extends AbstractControllerSchemaFactory {
    private static ExportCaseNotesFactory.ExportCaseNotesSchemaFactory __instance;

    static ExportCaseNotesFactory.ExportCaseNotesSchemaFactory getInstance() {
      synchronized (ExportCaseNotesFactory.ExportCaseNotesSchemaFactory.class) {
        if (null == ExportCaseNotesFactory.ExportCaseNotesSchemaFactory.__instance) {
            ExportCaseNotesFactory.ExportCaseNotesSchemaFactory.__instance = new ExportCaseNotesFactory.ExportCaseNotesSchemaFactory();
        }

        return ExportCaseNotesFactory.ExportCaseNotesSchemaFactory.__instance;
      }
    }

    private ExportCaseNotesSchemaFactory() {}

    protected final void initSchemaMaps() {
      synchronized (this) {
        if (null != this.schema) {
          return;
        }

          this.schema = new RequestSchema();
          this.schema.setRootPath("");

        //controller schema for controller method exportCaseNotes
        RequestSchema.JMethod method1 = this.addMethod("exportCaseNotes",
                "exportMastersSP/postDataSP",
                "POST",
                ExportCaseNotesResult.class,
                null,
                Collections.singletonList("application/json"),
                Collections.singletonList("application/json"));
        method1.setBaseUrl(BaseConfig.AppNodeIP);//"http://192.168.137.123:1234"
        method1.addParam("Content-Type",
                "HEADER",
                String.class,
                null,
                "",
                true);
        method1.addParam("body",
                "PLAIN",
                ExportCaseNotesRequest.class,
                null,
                "",
                true);
      }
    }

  }

}
