/*
  File generated by Magnet rest2mobile 1.1 - 8 Feb, 2018 11:48:07 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.updateDB.controller.api;


import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.importREST_Services.updateDB.model.beans.DBUpdateResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.updateDB.model.beans.GetDBUpdateRequest;

interface DBUpdate {

    /**
     * Generated from URL POST http://192.168.137.3:1234/data/tblDBupdate
     * POST data/tblDBupdate
     * @param contentType (original name : Content-Type) style:HEADER
     * @param body  style:PLAIN
     * @param listener
     * @return DBUpdateResult
     */
    Call<DBUpdateResult> getDBUpdate(
            String contentType,
            GetDBUpdateRequest body,
            StateChangedListener listener
    );


}
