/*
  File generated by Magnet rest2mobile 1.1 - 8 Feb, 2018 11:48:07 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.updateDB.controller.api;


import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.updateDB.model.beans.DBUpdateResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.updateDB.model.beans.GetDBUpdateRequest;

public class DBUpdateFactory extends ControllerFactory<DBUpdate> {
    public DBUpdateFactory(MagnetMobileClient magnetClient) {
        super(DBUpdate.class, DBUpdateFactory.DBUpdateSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller DBUpdate
    public static class DBUpdateSchemaFactory extends AbstractControllerSchemaFactory {
        private static DBUpdateFactory.DBUpdateSchemaFactory __instance;

        private DBUpdateSchemaFactory() {
        }

        static DBUpdateFactory.DBUpdateSchemaFactory getInstance() {
            synchronized (DBUpdateFactory.DBUpdateSchemaFactory.class) {
                if (null == DBUpdateFactory.DBUpdateSchemaFactory.__instance) {
                    DBUpdateFactory.DBUpdateSchemaFactory.__instance = new DBUpdateFactory.DBUpdateSchemaFactory();
                }

                return DBUpdateFactory.DBUpdateSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method getDBUpdate
                RequestSchema.JMethod method1 = this.addMethod("getDBUpdate",
                        "data/tblDBupdate",
                        "POST",
                        DBUpdateResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("Content-Type",
                        "HEADER",
                        String.class,
                        null,
                        "",
                        true);
                method1.addParam("body",
                        "PLAIN",
                        GetDBUpdateRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
