/*
  File generated by Magnet rest2mobile 1.1 - Feb 27, 2018 4:24:33 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.MastersRestAPI;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;


public interface MasterOthersRestAPI {

    /**
     * Generated from URL GET http://182.18.161.229/KDMCDB_JSON/Service.asmx/Get_Masters_OtherTables?TableId=0&IsUpdateMax=0
     * GET KDMCDB_JSON/Service.asmx/Get_Masters_OtherTables
     * @param tableId (original name : TableId) style:QUERY
     * @param isUpdateMax (original name : IsUpdateMax) style:QUERY
     * @param listener
     * @return String
     */
    Call<String> table1(
            String tableId,
            String masterId,
            String isUpdateMax,
            StateChangedListener listener
    );


}
