/*
  File generated by Magnet rest2mobile 1.1 - Feb 27, 2018 4:24:33 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.MastersRestAPI;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;


public class MasterOthersRestAPIFactory extends ControllerFactory<MasterOthersRestAPI> {
    public MasterOthersRestAPIFactory(MagnetMobileClient magnetClient) {
        super(MasterOthersRestAPI.class, MasterOthersRestAPIFactory.MasterOthersRestAPISchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller MasterOthersRestAPI
    public static class MasterOthersRestAPISchemaFactory extends AbstractControllerSchemaFactory {
        private static MasterOthersRestAPIFactory.MasterOthersRestAPISchemaFactory __instance;

        private MasterOthersRestAPISchemaFactory() {
        }

        static MasterOthersRestAPIFactory.MasterOthersRestAPISchemaFactory getInstance() {
            synchronized (MasterOthersRestAPIFactory.MasterOthersRestAPISchemaFactory.class) {
                if (null == MasterOthersRestAPIFactory.MasterOthersRestAPISchemaFactory.__instance) {
                    MasterOthersRestAPIFactory.MasterOthersRestAPISchemaFactory.__instance = new MasterOthersRestAPIFactory.MasterOthersRestAPISchemaFactory();
                }

                return MasterOthersRestAPIFactory.MasterOthersRestAPISchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method table1
                RequestSchema.JMethod method1 = this.addMethod("table1",
                        BaseConfig.AppNodeIP + "/Get_Masters_OtherTables",
                        "GET",
                        String.class,
                        null,
                        null,
                        Collections.singletonList("text/plain"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("TableId",
                        "QUERY",
                        String.class,
                        null,
                        "",
                        true);
                method1.addParam("MasterId",
                        "QUERY",
                        String.class,
                        null,
                        "",
                        true);
                method1.addParam("IsUpdateMax",
                        "QUERY",
                        String.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
