/*
  File generated by Magnet rest2mobile 1.1 - Sep 18, 2017 3:52:26 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.MastersRestAPI;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;


public class Masters_RESTAPIFactory extends ControllerFactory<Masters_RESTAPI> {
    public Masters_RESTAPIFactory(MagnetMobileClient magnetClient) {
        super(Masters_RESTAPI.class, Masters_RESTAPIFactory.Masters_RESTAPISchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller Masters_RESTAPI
    public static class Masters_RESTAPISchemaFactory extends AbstractControllerSchemaFactory {
        private static Masters_RESTAPIFactory.Masters_RESTAPISchemaFactory __instance;

        private Masters_RESTAPISchemaFactory() {
        }

        static Masters_RESTAPIFactory.Masters_RESTAPISchemaFactory getInstance() {
            synchronized (Masters_RESTAPIFactory.Masters_RESTAPISchemaFactory.class) {
                if (null == Masters_RESTAPIFactory.Masters_RESTAPISchemaFactory.__instance) {
                    Masters_RESTAPIFactory.Masters_RESTAPISchemaFactory.__instance = new Masters_RESTAPIFactory.Masters_RESTAPISchemaFactory();
                }

                return Masters_RESTAPIFactory.Masters_RESTAPISchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method table1
                RequestSchema.JMethod method1 = this.addMethod("table1",
                        BaseConfig.AppNodeIP + "/Get_Masters_Tables",
                        "GET",
                        String.class,
                        null,
                        null,
                        Collections.singletonList("text/plain"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("TableId",
                        "QUERY",
                        String.class,
                        null,
                        "",
                        true);
                method1.addParam("IsUpdateMax",
                        "QUERY",
                        String.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
