/*
  File generated by Magnet rest2mobile 1.1 - 8 Feb, 2018 1:39:17 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.getDoctorDetails.controller.api;


import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getDoctorDetails.model.beans.DoctorIdResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getDoctorDetails.model.beans.PostDoctorIdRequest;

public class DoctorDetailsFactory extends ControllerFactory<DoctorDetails> {
    public DoctorDetailsFactory(MagnetMobileClient magnetClient) {
        super(DoctorDetails.class, DoctorDetailsFactory.DoctorDetailsSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller DoctorDetails
    public static class DoctorDetailsSchemaFactory extends AbstractControllerSchemaFactory {
        private static DoctorDetailsFactory.DoctorDetailsSchemaFactory __instance;

        private DoctorDetailsSchemaFactory() {
        }

        static DoctorDetailsFactory.DoctorDetailsSchemaFactory getInstance() {
            synchronized (DoctorDetailsFactory.DoctorDetailsSchemaFactory.class) {
                if (null == DoctorDetailsFactory.DoctorDetailsSchemaFactory.__instance) {
                    DoctorDetailsFactory.DoctorDetailsSchemaFactory.__instance = new DoctorDetailsFactory.DoctorDetailsSchemaFactory();
                }

                return DoctorDetailsFactory.DoctorDetailsSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method postDoctorId
                RequestSchema.JMethod method1 = this.addMethod("postDoctorId",
                        "data/Get_DrRegInfo",
                        "POST",
                        DoctorIdResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("Content-Type",
                        "HEADER",
                        String.class,
                        null,
                        "",
                        true);
                method1.addParam("body",
                        "PLAIN",
                        PostDoctorIdRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
