/*
  File generated by Magnet rest2mobile 1.1 - 8 Feb, 2018 1:39:17 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.getDoctorDetails.controller.api;


import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getDoctorDetails.model.beans.DoctorIdResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getDoctorDetails.model.beans.PostDoctorIdRequest;

public interface DoctorDetails {

    /**
     * Generated from URL POST http://192.168.137.3:1234/data/Get_DrRegInfo
     * POST data/Get_DrRegInfo
     * @param contentType (original name : Content-Type) style:HEADER
     * @param body  style:PLAIN
     * @param listener
     * @return DoctorIdResult
     */
    Call<DoctorIdResult> postDoctorId(
            String contentType,
            PostDoctorIdRequest body,
            StateChangedListener listener
    );


}
