/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 6:43:40 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatIdDocIdMtestId.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatIdDocIdMtestId.model.beans.PosPatIdDocIdMtestIdRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatIdDocIdMtestId.model.beans.PosPatIdDocIdMtestIdResult;

public class PostPatIdDocIdMtestIdFactory extends ControllerFactory<PostPatIdDocIdMtestId> {
    public PostPatIdDocIdMtestIdFactory(MagnetMobileClient magnetClient) {
        super(PostPatIdDocIdMtestId.class, PostPatIdDocIdMtestIdSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PostPatIdDocIdMtestId
    public static class PostPatIdDocIdMtestIdSchemaFactory extends AbstractControllerSchemaFactory {
        private static PostPatIdDocIdMtestIdSchemaFactory __instance = null;

        private PostPatIdDocIdMtestIdSchemaFactory() {
        }

        static PostPatIdDocIdMtestIdSchemaFactory getInstance() {
            synchronized (PostPatIdDocIdMtestIdSchemaFactory.class) {
                if (null == __instance) {
                    __instance = new PostPatIdDocIdMtestIdSchemaFactory();
                }

                return __instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != schema) {
                    return;
                }

                schema = new RequestSchema();
                schema.setRootPath("");

                //controller schema for controller method posPatIdDocIdMtestId
                JMethod method1 = addMethod("postDoctorIdPatidMtestId",
                        "importMastersSP/postDoctorIdPatidMtestId",
                        "POST",
                        PosPatIdDocIdMtestIdResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("body",
                        "PLAIN",
                        PosPatIdDocIdMtestIdRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
