/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 6:43:40 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatIdDocIdMtestId.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatIdDocIdMtestId.model.beans.PosPatIdDocIdMtestIdRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatIdDocIdMtestId.model.beans.PosPatIdDocIdMtestIdResult;

interface PostPatIdDocIdMtestId {

    /**
     * Generated from URL POST http://192.168.137.143:1234/importMasters/postPatIdDocIdMtestId
     * POST importMasters/postPatIdDocIdMtestId
     * @param body  style:PLAIN
     * @param listener
     * @return PosPatIdDocIdMtestIdResult
     */
    Call<PosPatIdDocIdMtestIdResult> posPatIdDocIdMtestId(
            PosPatIdDocIdMtestIdRequest body,
            StateChangedListener listener
    );


}
