/**
 * File generated by Magnet rest2mobile 1.1 - 17 Apr, 2018 9:56:32 AM
 * @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.NewImportMaster.model.beans;


/**
 * Generated from json example
{
  "IsUpdateMax" : "0",
  "TableId" : "0",
  "MasterId" : "0"
}

 */

public class GetNewMastersRequest {

  
@com.google.gson.annotations.SerializedName("IsUpdateMax")
  private String isUpdateMax;

  
@com.google.gson.annotations.SerializedName("MasterId")
  private String masterId;

  
@com.google.gson.annotations.SerializedName("TableId")
  private String tableId;

  public String getIsUpdateMax() {
    return isUpdateMax;
  }
  public String getMasterId() {
    return masterId;
  }
  public String getTableId() {
    return tableId;
  }


  public void setIsUpdateMax(String isUpdateMax) {
    this.isUpdateMax = isUpdateMax;
  }

  public void setMasterId(String masterId) {
    this.masterId = masterId;
  }

  public void setTableId(String tableId) {
    this.tableId = tableId;
  }

  /**
  * Builder for GetNewMastersRequest
  **/
  public static class GetNewMastersRequestBuilder {
    private GetNewMastersRequest toBuild = new GetNewMastersRequest();

    public GetNewMastersRequestBuilder() {
    }

    public GetNewMastersRequest build() {
      return toBuild;
    }

    public GetNewMastersRequestBuilder isUpdateMax(String value) {
      toBuild.isUpdateMax = value;
      return this;
    }
    public GetNewMastersRequestBuilder masterId(String value) {
      toBuild.masterId = value;
      return this;
    }
    public GetNewMastersRequestBuilder tableId(String value) {
      toBuild.tableId = value;
      return this;
    }
  }
}
