/**
 * File generated by Magnet rest2mobile 1.1 - 17 Apr, 2018 9:56:32 AM
 * @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.NewImportMaster.model.beans;


/**
 * Generated from json example
{
  "Results" : "[]"
}

 */

public class NewMastersResult {

  
@com.google.gson.annotations.SerializedName("Results")
  private String results;

  public String getResults() {
    return this.results;
  }

  /**
  * Builder for NewMastersResult
  **/
  public static class NewMastersResultBuilder {
    private final NewMastersResult toBuild = new NewMastersResult();

    public NewMastersResultBuilder() {
    }

    public NewMastersResult build() {
      return this.toBuild;
    }

    public NewMastersResult.NewMastersResultBuilder results(String value) {
        this.toBuild.results = value;
      return this;
    }
  }
}
