/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 11:12:57 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postDoctorId.model.beans;


/**
 * Generated from json example
 {
 "Results" : ""
 }

 */

public class DoctorIdResult {


    @com.google.gson.annotations.SerializedName("Results")
    private String results;

    public DoctorIdResult() {
    }

    public final String getResults() {
        return this.results;
    }

    public void setResults(String results) {
        this.results = results;
    }

    /**
     * Builder for DoctorIdResult
     **/
    public static class DoctorIdResultBuilder {
        private final DoctorIdResult toBuild = new DoctorIdResult();

        public DoctorIdResultBuilder() {
        }

        public final DoctorIdResult build() {
            return this.toBuild;
        }

        public final DoctorIdResult.DoctorIdResultBuilder results(String value) {
            this.toBuild.setResults(value);
            return this;
        }
    }
}
