/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 11:12:57 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postDoctorId.model.beans;


/**
 * Generated from json example
 {
 "DoctorID" : "0",
 "MethodName" : "3"
 }

 */

public class PostDoctorIdRequest {


    @com.google.gson.annotations.SerializedName("DoctorID")
    private String doctorID;


    @com.google.gson.annotations.SerializedName("MethodName")
    private String methodName;

    public PostDoctorIdRequest() {
    }

    public final String getDoctorID() {
        return this.doctorID;
    }

    public final void setDoctorID(String doctorID) {
        this.doctorID = doctorID;
    }

    public final String getMethodName() {
        return this.methodName;
    }

    public final void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * Builder for PostDoctorIdRequest
     **/
    public static class PostDoctorIdRequestBuilder {
        private final PostDoctorIdRequest toBuild = new PostDoctorIdRequest();

        public PostDoctorIdRequestBuilder() {
        }

        public final PostDoctorIdRequest build() {
            return this.toBuild;
        }

        public final PostDoctorIdRequest.PostDoctorIdRequestBuilder doctorID(String value) {
            this.toBuild.setDoctorID(value);
            return this;
        }

        public final PostDoctorIdRequest.PostDoctorIdRequestBuilder methodName(String value) {
            this.toBuild.setMethodName(value);
            return this;
        }
    }
}
