/*
  File generated by Magnet rest2mobile 1.1 - Nov 2, 2017 12:56:35 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.insertTable.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.insertTable.model.beans.PostTableDataRequest;
import kdmc_kumar.Webservices_NodeJSON.insertTable.model.beans.TableDataResult;

interface PostTableData {

    /**
     * Generated from URL POST http://localhost:1234/data/InsertClinicalInformationDemo
     * POST data/InsertClinicalInformationDemo
     * @param contentType (original name : Content-Type) style:HEADER
     * @param body  style:PLAIN
     * @param listener
     * @return TableDataResult
     */
    Call<TableDataResult> postTableData(
            String contentType,
            PostTableDataRequest body,
            StateChangedListener listener
    );


}
