/*
  File generated by Magnet rest2mobile 1.1 - Nov 2, 2017 12:56:35 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.insertTable.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.insertTable.model.beans.PostTableDataRequest;
import kdmc_kumar.Webservices_NodeJSON.insertTable.model.beans.TableDataResult;

public class PostTableDataFactory extends ControllerFactory<PostTableData> {
    public PostTableDataFactory(MagnetMobileClient magnetClient) {
        super(PostTableData.class, PostTableDataFactory.PostTableDataSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PostTableData
    public static class PostTableDataSchemaFactory extends AbstractControllerSchemaFactory {
        private static PostTableDataFactory.PostTableDataSchemaFactory __instance;

        private PostTableDataSchemaFactory() {
        }

        static PostTableDataFactory.PostTableDataSchemaFactory getInstance() {
            synchronized (PostTableDataFactory.PostTableDataSchemaFactory.class) {
                if (null == PostTableDataFactory.PostTableDataSchemaFactory.__instance) {
                    PostTableDataFactory.PostTableDataSchemaFactory.__instance = new PostTableDataFactory.PostTableDataSchemaFactory();
                }

                return PostTableDataFactory.PostTableDataSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method postTableData
                RequestSchema.JMethod method1 = this.addMethod("postTableData",
                        "data/ExportAllTables",
                        "POST",
                        TableDataResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("Content-Type",
                        "HEADER",
                        String.class,
                        null,
                        "",
                        true);
                method1.addParam("body",
                        "PLAIN",
                        PostTableDataRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
