/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 6:36:07 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postImmunizationInfo.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postImmunizationInfo.model.beans.PosImmunizationInfoRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postImmunizationInfo.model.beans.PosImmunizationInfoResult;

public interface PostImmunizationInfo {

    /**
     * Generated from URL POST http://192.168.137.143:1234/importMasters/Sel_Vaccinationtemp_webupdate
     * POST importMasters/Sel_Vaccinationtemp_webupdate
     * @param body  style:PLAIN
     * @param listener
     * @return PosImmunizationInfoResult
     */
    Call<PosImmunizationInfoResult> posImmunizationInfo(
            PosImmunizationInfoRequest body,
            StateChangedListener listener
    );


}
