/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 6:36:07 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postImmunizationInfo.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postImmunizationInfo.model.beans.PosImmunizationInfoRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postImmunizationInfo.model.beans.PosImmunizationInfoResult;

public class PostImmunizationInfoFactory extends ControllerFactory<PostImmunizationInfo> {
    public PostImmunizationInfoFactory(MagnetMobileClient magnetClient) {
        super(PostImmunizationInfo.class, PostImmunizationInfoFactory.PostImmunizationInfoSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PostImmunizationInfo
    public static class PostImmunizationInfoSchemaFactory extends AbstractControllerSchemaFactory {
        private static PostImmunizationInfoFactory.PostImmunizationInfoSchemaFactory __instance;

        private PostImmunizationInfoSchemaFactory() {
        }

        static PostImmunizationInfoFactory.PostImmunizationInfoSchemaFactory getInstance() {
            synchronized (PostImmunizationInfoFactory.PostImmunizationInfoSchemaFactory.class) {
                if (null == PostImmunizationInfoFactory.PostImmunizationInfoSchemaFactory.__instance) {
                    PostImmunizationInfoFactory.PostImmunizationInfoSchemaFactory.__instance = new PostImmunizationInfoFactory.PostImmunizationInfoSchemaFactory();
                }

                return PostImmunizationInfoFactory.PostImmunizationInfoSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method posImmunizationInfo
                RequestSchema.JMethod method1 = this.addMethod("posImmunizationInfo",
                        "importMastersSP/Sel_Vaccinationtemp_webupdate",
                        "POST",
                        PosImmunizationInfoResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("body",
                        "PLAIN",
                        PosImmunizationInfoRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
