/*
  File generated by Magnet rest2mobile 1.1 - 27 Mar, 2018 5:10:19 PM
  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.exportCaseNotes.model.beans;


/**
 * Generated from json example
{
  "Results" : ""
}

 */

public class ExportCaseNotesResult {

  
@com.google.gson.annotations.SerializedName("Results")
  private String results;

    public ExportCaseNotesResult() {
    }

    public final String getResults() {
    return this.results;
  }

  public void setResults(String results) {
    this.results = results;
  }

  /**
  * Builder for ExportCaseNotesResult
  **/
  public static class ExportCaseNotesResultBuilder {
    private final ExportCaseNotesResult toBuild = new ExportCaseNotesResult();

    public ExportCaseNotesResultBuilder() {
    }

    public final ExportCaseNotesResult build() {
      return this.toBuild;
    }

    public final ExportCaseNotesResult.ExportCaseNotesResultBuilder results(String value) {
        this.toBuild.setResults(value);
      return this;
    }
  }
}
