/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 6:43:40 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatIdDocIdMtestId.model.beans;


/**
 * Generated from json example
 {
 "PatId" : "",
 "DocId" : "",
 "MtestId" : "",
 "MethodName" : ""
 }

 */

public class PosPatIdDocIdMtestIdRequest {


    @com.google.gson.annotations.SerializedName("DocId")
    private String docId;


    @com.google.gson.annotations.SerializedName("MethodName")
    private String methodName;


    @com.google.gson.annotations.SerializedName("MtestId")
    private String mtestId;


    @com.google.gson.annotations.SerializedName("PatId")
    private String patId;

    public PosPatIdDocIdMtestIdRequest() {
    }

    public final String getDocId() {
        return this.docId;
    }

    public final void setDocId(String docId) {
        this.docId = docId;
    }

    public final String getMethodName() {
        return this.methodName;
    }

    public final void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    public final String getMtestId() {
        return this.mtestId;
    }

    public final void setMtestId(String mtestId) {
        this.mtestId = mtestId;
    }

    public final String getPatId() {
        return this.patId;
    }

    public final void setPatId(String patId) {
        this.patId = patId;
    }

    /**
     * Builder for PosPatIdDocIdMtestIdRequest
     **/
    public static class PosPatIdDocIdMtestIdRequestBuilder {
        private final PosPatIdDocIdMtestIdRequest toBuild = new PosPatIdDocIdMtestIdRequest();

        public PosPatIdDocIdMtestIdRequestBuilder() {
        }

        public final PosPatIdDocIdMtestIdRequest build() {
            return this.toBuild;
        }

        public final PosPatIdDocIdMtestIdRequest.PosPatIdDocIdMtestIdRequestBuilder docId(String value) {
            this.toBuild.setDocId(value);
            return this;
        }

        public final PosPatIdDocIdMtestIdRequest.PosPatIdDocIdMtestIdRequestBuilder methodName(String value) {
            this.toBuild.setMethodName(value);
            return this;
        }

        public final PosPatIdDocIdMtestIdRequest.PosPatIdDocIdMtestIdRequestBuilder mtestId(String value) {
            this.toBuild.setMtestId(value);
            return this;
        }

        public final PosPatIdDocIdMtestIdRequest.PosPatIdDocIdMtestIdRequestBuilder patId(String value) {
            this.toBuild.setPatId(value);
            return this;
        }
    }
}
