/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 6:43:40 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatIdDocIdMtestId.model.beans;


/**
 * Generated from json example
 {
 "PatId" : "",
 "DocId" : "",
 "MtestId" : "",
 "MethodName" : ""
 }

 */

public class PosPatIdDocIdMtestIdRequest {


    @com.google.gson.annotations.SerializedName("DocId")
    private String docId = null;


    @com.google.gson.annotations.SerializedName("MethodName")
    private String methodName = null;


    @com.google.gson.annotations.SerializedName("MtestId")
    private String mtestId = null;


    @com.google.gson.annotations.SerializedName("PatId")
    private String patId = null;

    public PosPatIdDocIdMtestIdRequest() {
    }

    public final String getDocId() {
        return docId;
    }

    public final void setDocId(String docId) {
        this.docId = docId;
    }

    public final String getMethodName() {
        return methodName;
    }

    public final void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    public final String getMtestId() {
        return mtestId;
    }

    public final void setMtestId(String mtestId) {
        this.mtestId = mtestId;
    }

    public final String getPatId() {
        return patId;
    }

    public final void setPatId(String patId) {
        this.patId = patId;
    }

    /**
     * Builder for PosPatIdDocIdMtestIdRequest
     **/
    public static class PosPatIdDocIdMtestIdRequestBuilder {
        private final PosPatIdDocIdMtestIdRequest toBuild = new PosPatIdDocIdMtestIdRequest();

        public PosPatIdDocIdMtestIdRequestBuilder() {
        }

        public final PosPatIdDocIdMtestIdRequest build() {
            return toBuild;
        }

        public final PosPatIdDocIdMtestIdRequestBuilder docId(String value) {
            toBuild.setDocId(value);
            return this;
        }

        public final PosPatIdDocIdMtestIdRequestBuilder methodName(String value) {
            toBuild.setMethodName(value);
            return this;
        }

        public final PosPatIdDocIdMtestIdRequestBuilder mtestId(String value) {
            toBuild.setMtestId(value);
            return this;
        }

        public final PosPatIdDocIdMtestIdRequestBuilder patId(String value) {
            toBuild.setPatId(value);
            return this;
        }
    }
}
