/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 6:43:40 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatIdDocIdMtestId.model.beans;


/**
 * Generated from json example
 {
 "Results" : ""
 }

 */

public class PosPatIdDocIdMtestIdResult {


    @com.google.gson.annotations.SerializedName("Results")
    private String results;

    public PosPatIdDocIdMtestIdResult() {
    }

    public final String getResults() {
        return this.results;
    }

    public void setResults(String results) {
        this.results = results;
    }

    /**
     * Builder for PosPatIdDocIdMtestIdResult
     **/
    public static class PosPatIdDocIdMtestIdResultBuilder {
        private final PosPatIdDocIdMtestIdResult toBuild = new PosPatIdDocIdMtestIdResult();

        public PosPatIdDocIdMtestIdResultBuilder() {
        }

        public final PosPatIdDocIdMtestIdResult build() {
            return this.toBuild;
        }

        public final PosPatIdDocIdMtestIdResult.PosPatIdDocIdMtestIdResultBuilder results(String value) {
            this.toBuild.setResults(value);
            return this;
        }
    }
}
