/*
  File generated by Magnet rest2mobile 1.1 - Dec 15, 2017 6:58:30 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatIdDocIdMtestId.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatIdDocIdMtestId.model.beans.PatIdDocIdMtestIdResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatIdDocIdMtestId.model.beans.PostPatIdDocIdMtestIdRequest;


public class PatIdDocIdMtestIdFactory extends ControllerFactory<PatIdDocIdMtestId> {
    public PatIdDocIdMtestIdFactory(MagnetMobileClient magnetClient) {
        super(PatIdDocIdMtestId.class, PatIdDocIdMtestIdSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PatIdDocIdMtestId
    public static class PatIdDocIdMtestIdSchemaFactory extends AbstractControllerSchemaFactory {
        private static PatIdDocIdMtestIdSchemaFactory __instance = null;

        private PatIdDocIdMtestIdSchemaFactory() {
        }

        static PatIdDocIdMtestIdSchemaFactory getInstance() {
            synchronized (PatIdDocIdMtestIdSchemaFactory.class) {
                if (null == __instance) {
                    __instance = new PatIdDocIdMtestIdSchemaFactory();
                }

                return __instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != schema) {
                    return;
                }

                schema = new RequestSchema();
                schema.setRootPath("");

                //controller schema for controller method postPatIdDocIdMtestId
                JMethod method1 = addMethod("postPatIdDocIdMtestId",
                        "exportMasters/postData",
                        "POST",
                        PatIdDocIdMtestIdResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("Content-Type",
                        "HEADER",
                        String.class,
                        null,
                        "",
                        true);
                method1.addParam("body",
                        "PLAIN",
                        PostPatIdDocIdMtestIdRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
