/**
 * File generated by Magnet rest2mobile 1.1 - 17 Apr, 2018 9:56:32 AM
 * @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.NewImportMaster.controller.api;


import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.NewImportMaster.model.beans.GetNewMastersRequest;
import kdmc_kumar.Webservices_NodeJSON.NewImportMaster.model.beans.NewMastersResult;

public interface NewImportMaster {

  /**
   * Generated from URL POST http://127.0.0.1:1234/mastersSP/getNewMasterTables
   * POST mastersSP/getNewMasterTables
   * @param contentType (original name : Content-Type) style:HEADER
   * @param body  style:PLAIN
   * @param listener
   * @return NewMastersResult
   */
  Call<NewMastersResult> getNewMasters(
          String contentType,
          GetNewMastersRequest body,
          StateChangedListener listener
  );


}
