/**
 * File generated by Magnet rest2mobile 1.1 - 17 Apr, 2018 9:56:32 AM
 * @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.NewImportMaster.controller.api;


import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Arrays;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.NewImportMaster.model.beans.GetNewMastersRequest;
import kdmc_kumar.Webservices_NodeJSON.NewImportMaster.model.beans.NewMastersResult;

public class NewImportMasterFactory extends ControllerFactory<NewImportMaster> {
  public NewImportMasterFactory(MagnetMobileClient magnetClient) {
    super(NewImportMaster.class, NewImportMasterSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller NewImportMaster
  public static class NewImportMasterSchemaFactory extends AbstractControllerSchemaFactory {
    private static NewImportMasterSchemaFactory __instance;

    public static synchronized NewImportMasterSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new NewImportMasterSchemaFactory();
      }

      return __instance;
    }

    private NewImportMasterSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getNewMasters
      JMethod method1 = addMethod("getNewMasters",
        "mastersSP/getNewMasterTables",
        "POST",
        NewMastersResult.class,
        null,
        Arrays.asList("application/json"),
        Arrays.asList("application/json"));
      method1.setBaseUrl(BaseConfig.AppNodeIP);
      method1.addParam("Content-Type",
        "HEADER",
        String.class,
        null,
        "",
        true);
      method1.addParam("body",
        "PLAIN",
        GetNewMastersRequest.class,
        null,
        "",
        true);
    }

  }

}
