/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 12:23:03 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postIsUpdateMax.model.beans;


/**
 * Generated from json example
 {
 "Results" : ""
 }

 */

public class IsUpdateMaxResult {


    @com.google.gson.annotations.SerializedName("Results")
    private String results = null;

    public IsUpdateMaxResult() {
    }

    public final String getResults() {
        return results;
    }

    public void setResults(String results) {
        this.results = results;
    }

    /**
     * Builder for IsUpdateMaxResult
     **/
    public static class IsUpdateMaxResultBuilder {
        private final IsUpdateMaxResult toBuild = new IsUpdateMaxResult();

        public IsUpdateMaxResultBuilder() {
        }

        public final IsUpdateMaxResult build() {
            return toBuild;
        }

        public final IsUpdateMaxResultBuilder results(String value) {
            toBuild.setResults(value);
            return this;
        }
    }
}
