/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 12:23:03 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postIsUpdateMax.model.beans;


/**
 * Generated from json example
 {
 "IsUpdateMax" : "0",
 "MethodName" : "3"
 }

 */

public class PostIsUpdateMaxRequest {


    @com.google.gson.annotations.SerializedName("IsUpdateMax")
    private String isUpdateMax;


    @com.google.gson.annotations.SerializedName("MethodName")
    private String methodName;

    public PostIsUpdateMaxRequest() {
    }

    public final String getIsUpdateMax() {
        return this.isUpdateMax;
    }

    public final void setIsUpdateMax(String isUpdateMax) {
        this.isUpdateMax = isUpdateMax;
    }

    public final String getMethodName() {
        return this.methodName;
    }

    public final void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * Builder for PostIsUpdateMaxRequest
     **/
    public static class PostIsUpdateMaxRequestBuilder {
        private final PostIsUpdateMaxRequest toBuild = new PostIsUpdateMaxRequest();

        public PostIsUpdateMaxRequestBuilder() {
        }

        public final PostIsUpdateMaxRequest build() {
            return this.toBuild;
        }

        public final PostIsUpdateMaxRequest.PostIsUpdateMaxRequestBuilder isUpdateMax(String value) {
            this.toBuild.setIsUpdateMax(value);
            return this;
        }

        public final PostIsUpdateMaxRequest.PostIsUpdateMaxRequestBuilder methodName(String value) {
            this.toBuild.setMethodName(value);
            return this;
        }
    }
}
