/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 1:42:33 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatientIdList.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatientIdList.model.beans.PatientIdListResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatientIdList.model.beans.PostPatientIdListRequest;

public class PostPatientIdListFactory extends ControllerFactory<PostPatientIdList> {
    public PostPatientIdListFactory(MagnetMobileClient magnetClient) {
        super(PostPatientIdList.class, PostPatientIdListSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PostPatientIdList
    public static class PostPatientIdListSchemaFactory extends AbstractControllerSchemaFactory {
        private static PostPatientIdListSchemaFactory __instance = null;

        private PostPatientIdListSchemaFactory() {
        }

        static PostPatientIdListSchemaFactory getInstance() {
            synchronized (PostPatientIdListSchemaFactory.class) {
                if (null == __instance) {
                    __instance = new PostPatientIdListSchemaFactory();
                }

                return __instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != schema) {
                    return;
                }

                schema = new RequestSchema();
                schema.setRootPath("");

                //controller schema for controller method postPatientIdList
                JMethod method1 = addMethod("postPatientIdList",
                        "importMastersSP/postPatientIdList",
                        "POST",
                        PatientIdListResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
              //  method1.setBaseUrl("http://192.168.137.78:1234/");
                method1.addParam("body",
                        "PLAIN",
                        PostPatientIdListRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
