/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 1:42:33 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatientIdList.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatientIdList.model.beans.PatientIdListResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatientIdList.model.beans.PostPatientIdListRequest;

public class PostPatientIdListFactory extends ControllerFactory<PostPatientIdList> {
    public PostPatientIdListFactory(MagnetMobileClient magnetClient) {
        super(PostPatientIdList.class, PostPatientIdListFactory.PostPatientIdListSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PostPatientIdList
    public static class PostPatientIdListSchemaFactory extends AbstractControllerSchemaFactory {
        private static PostPatientIdListFactory.PostPatientIdListSchemaFactory __instance;

        private PostPatientIdListSchemaFactory() {
        }

        static PostPatientIdListFactory.PostPatientIdListSchemaFactory getInstance() {
            synchronized (PostPatientIdListFactory.PostPatientIdListSchemaFactory.class) {
                if (null == PostPatientIdListFactory.PostPatientIdListSchemaFactory.__instance) {
                    PostPatientIdListFactory.PostPatientIdListSchemaFactory.__instance = new PostPatientIdListFactory.PostPatientIdListSchemaFactory();
                }

                return PostPatientIdListFactory.PostPatientIdListSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method postPatientIdList
                RequestSchema.JMethod method1 = this.addMethod("postPatientIdList",
                        "importMastersSP/postPatientIdList",
                        "POST",
                        PatientIdListResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("body",
                        "PLAIN",
                        PostPatientIdListRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
