/*
  File generated by Magnet rest2mobile 1.1 - Dec 15, 2017 6:58:30 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatIdDocIdMtestId.model.beans;


/**
 * Generated from json example
 {
 "Results" : "[{\"Id\":3565}]",
 "LocalIds" : "{\"LocalId\":[\"1\"]}"
 }

 */

public class PatIdDocIdMtestIdResult {


    @com.google.gson.annotations.SerializedName("LocalIds")
    private String localIds;


    @com.google.gson.annotations.SerializedName("Results")
    private String results;

    public PatIdDocIdMtestIdResult() {
    }

    public final String getLocalIds() {
        return this.localIds;
    }

    public final String getResults() {
        return this.results;
    }

    public void setLocalIds(String localIds) {
        this.localIds = localIds;
    }

    public void setResults(String results) {
        this.results = results;
    }

    /**
     * Builder for PatIdDocIdMtestIdResult
     **/
    public static class PatIdDocIdMtestIdResultBuilder {
        private final PatIdDocIdMtestIdResult toBuild = new PatIdDocIdMtestIdResult();

        public PatIdDocIdMtestIdResultBuilder() {
        }

        public final PatIdDocIdMtestIdResult build() {
            return this.toBuild;
        }

        public final PatIdDocIdMtestIdResult.PatIdDocIdMtestIdResultBuilder localIds(String value) {
            this.toBuild.setLocalIds(value);
            return this;
        }

        public final PatIdDocIdMtestIdResult.PatIdDocIdMtestIdResultBuilder results(String value) {
            this.toBuild.setResults(value);
            return this;
        }
    }
}
