/*
  File generated by Magnet rest2mobile 1.1 - Dec 15, 2017 6:58:30 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatIdDocIdMtestId.model.beans;


/**
 * Generated from json example
 {
 "JsonValue" : "",
 "MethodName" : "insertDoctorReferralCertificate"
 }

 */

public class PostPatIdDocIdMtestIdRequest {


    @com.google.gson.annotations.SerializedName("JsonValue")
    private String jsonValue = null;


    @com.google.gson.annotations.SerializedName("MethodName")
    private String methodName = null;

    public PostPatIdDocIdMtestIdRequest() {
    }

    public final String getJsonValue() {
        return jsonValue;
    }

    public final void setJsonValue(String jsonValue) {
        this.jsonValue = jsonValue;
    }

    public final String getMethodName() {
        return methodName;
    }

    public final void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * Builder for PostPatIdDocIdMtestIdRequest
     **/
    public static class PostPatIdDocIdMtestIdRequestBuilder {
        private final PostPatIdDocIdMtestIdRequest toBuild = new PostPatIdDocIdMtestIdRequest();

        public PostPatIdDocIdMtestIdRequestBuilder() {
        }

        public final PostPatIdDocIdMtestIdRequest build() {
            return toBuild;
        }

        public final PostPatIdDocIdMtestIdRequestBuilder jsonValue(String value) {
            toBuild.setJsonValue(value);
            return this;
        }

        public final PostPatIdDocIdMtestIdRequestBuilder methodName(String value) {
            toBuild.setMethodName(value);
            return this;
        }
    }
}
