/*
  File generated by Magnet rest2mobile 1.1 - Dec 15, 2017 6:58:30 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postPatIdDocIdMtestId.model.beans;


/**
 * Generated from json example
 {
 "JsonValue" : "",
 "MethodName" : "insertDoctorReferralCertificate"
 }

 */

public class PostPatIdDocIdMtestIdRequest {


    @com.google.gson.annotations.SerializedName("JsonValue")
    private String jsonValue;


    @com.google.gson.annotations.SerializedName("MethodName")
    private String methodName;

    public PostPatIdDocIdMtestIdRequest() {
    }

    public final String getJsonValue() {
        return this.jsonValue;
    }

    public final void setJsonValue(String jsonValue) {
        this.jsonValue = jsonValue;
    }

    public final String getMethodName() {
        return this.methodName;
    }

    public final void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * Builder for PostPatIdDocIdMtestIdRequest
     **/
    public static class PostPatIdDocIdMtestIdRequestBuilder {
        private final PostPatIdDocIdMtestIdRequest toBuild = new PostPatIdDocIdMtestIdRequest();

        public PostPatIdDocIdMtestIdRequestBuilder() {
        }

        public final PostPatIdDocIdMtestIdRequest build() {
            return this.toBuild;
        }

        public final PostPatIdDocIdMtestIdRequest.PostPatIdDocIdMtestIdRequestBuilder jsonValue(String value) {
            this.toBuild.setJsonValue(value);
            return this;
        }

        public final PostPatIdDocIdMtestIdRequest.PostPatIdDocIdMtestIdRequestBuilder methodName(String value) {
            this.toBuild.setMethodName(value);
            return this;
        }
    }
}
