/*
  File generated by Magnet rest2mobile 1.1 - 9 Mar, 2018 12:44:20 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.generatePDFNode.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Arrays;
import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.generatePDFNode.model.beans.GetPDFNodeJsRequest;
import kdmc_kumar.Webservices_NodeJSON.generatePDFNode.model.beans.PDFNodeJsResult;


public class GeneratePDFNodeFactory extends ControllerFactory<GeneratePDFNode> {
    public GeneratePDFNodeFactory(MagnetMobileClient magnetClient) {
        super(GeneratePDFNode.class, GeneratePDFNodeSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller GeneratePDFNode
    public static class GeneratePDFNodeSchemaFactory extends AbstractControllerSchemaFactory {
        private static GeneratePDFNodeSchemaFactory __instance = null;

        private GeneratePDFNodeSchemaFactory() {
        }

        static GeneratePDFNodeSchemaFactory getInstance() {
            synchronized (GeneratePDFNodeSchemaFactory.class) {
                if (null == __instance) {
                    __instance = new GeneratePDFNodeSchemaFactory();
                }

                return __instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != schema) {
                    return;
                }

                schema = new RequestSchema();
                schema.setRootPath("");

                //controller schema for controller method getPDFNodeJs
                JMethod method1 = addMethod("getPDFNodeJs",
                        "ExportMasters/kdmcPDF",
                        "POST",
                        PDFNodeJsResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("Content-Type",
                        "HEADER",
                        String.class,
                        null,
                        "",
                        true);
                method1.addParam("body",
                        "PLAIN",
                        GetPDFNodeJsRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
