/*
  File generated by Magnet rest2mobile 1.1 - 8 Feb, 2018 12:31:43 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.checkCredential.controller.api;


import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.checkCredential.model.beans.PostUsernamePasswordRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.checkCredential.model.beans.UsernamePasswordResult;

public class CheckLoginFactory extends ControllerFactory<CheckLogin> {
    public CheckLoginFactory(MagnetMobileClient magnetClient) {
        super(CheckLogin.class, CheckLoginSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller CheckLogin
    public static class CheckLoginSchemaFactory extends AbstractControllerSchemaFactory {
        private static CheckLoginSchemaFactory __instance = null;

        private CheckLoginSchemaFactory() {
        }

        static CheckLoginSchemaFactory getInstance() {
            synchronized (CheckLoginSchemaFactory.class) {
                if (null == __instance) {
                    __instance = new CheckLoginSchemaFactory();
                }

                return __instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != schema) {
                    return;
                }

                schema = new RequestSchema();
                schema.setRootPath("");

                //controller schema for controller method postUsernamePassword
                JMethod method1 = addMethod("postUsernamePassword",
                        "data/login",
                        "POST",
                        UsernamePasswordResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("Content-Type",
                        "HEADER",
                        String.class,
                        null,
                        "",
                        true);
                method1.addParam("body",
                        "PLAIN",
                        PostUsernamePasswordRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
