/*
  File generated by Magnet rest2mobile 1.1 - 8 Feb, 2018 12:31:43 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.checkCredential.controller.api;


import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.importREST_Services.checkCredential.model.beans.PostUsernamePasswordRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.checkCredential.model.beans.UsernamePasswordResult;

public interface CheckLogin {

    /**
     * Generated from URL POST http://192.168.137.3:1234/data/login
     * POST data/login
     * @param contentType (original name : Content-Type) style:HEADER
     * @param body  style:PLAIN
     * @param listener
     * @return UsernamePasswordResult
     */
    Call<UsernamePasswordResult> postUsernamePassword(
            String contentType,
            PostUsernamePasswordRequest body,
            StateChangedListener listener
    );


}
