/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 11:12:57 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postDoctorId.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postDoctorId.model.beans.DoctorIdResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postDoctorId.model.beans.PostDoctorIdRequest;

public interface PostDoctorId {

    /**
     * Generated from URL POST http://192.168.137.1:1234/importMasters/postDoctorId
     * POST importMasters/postDoctorId
     * @param body  style:PLAIN
     * @param listener
     * @return DoctorIdResult
     */
    Call<DoctorIdResult> postDoctorId(
            PostDoctorIdRequest body,
            StateChangedListener listener
    );


}
