/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 11:12:57 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postDoctorId.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postDoctorId.model.beans.DoctorIdResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postDoctorId.model.beans.PostDoctorIdRequest;

public class PostDoctorIdFactory extends ControllerFactory<PostDoctorId> {
    public PostDoctorIdFactory(MagnetMobileClient magnetClient) {
        super(PostDoctorId.class, PostDoctorIdFactory.PostDoctorIdSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PostDoctorId
    public static class PostDoctorIdSchemaFactory extends AbstractControllerSchemaFactory {
        private static PostDoctorIdFactory.PostDoctorIdSchemaFactory __instance;

        private PostDoctorIdSchemaFactory() {
        }

        static PostDoctorIdFactory.PostDoctorIdSchemaFactory getInstance() {
            synchronized (PostDoctorIdFactory.PostDoctorIdSchemaFactory.class) {
                if (null == PostDoctorIdFactory.PostDoctorIdSchemaFactory.__instance) {
                    PostDoctorIdFactory.PostDoctorIdSchemaFactory.__instance = new PostDoctorIdFactory.PostDoctorIdSchemaFactory();
                }

                return PostDoctorIdFactory.PostDoctorIdSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method postDoctorId
                RequestSchema.JMethod method1 = this.addMethod("postDoctorId",
                        "importMastersSP/postDoctorId",
                        "POST",
                        DoctorIdResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("body",
                        "PLAIN",
                        PostDoctorIdRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
