/*
  File generated by Magnet rest2mobile 1.1 - Jan 24, 2018 12:21:20 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.getUpdateDB.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getUpdateDB.model.beans.GetUpdateDBRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getUpdateDB.model.beans.UpdateDBResult;


public class UpdateDBFactory extends ControllerFactory<UpdateDB> {
    public UpdateDBFactory(MagnetMobileClient magnetClient) {
        super(UpdateDB.class, UpdateDBFactory.UpdateDBSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller UpdateDB
    public static class UpdateDBSchemaFactory extends AbstractControllerSchemaFactory {
        private static UpdateDBFactory.UpdateDBSchemaFactory __instance;

        private UpdateDBSchemaFactory() {
        }

        static UpdateDBFactory.UpdateDBSchemaFactory getInstance() {
            synchronized (UpdateDBFactory.UpdateDBSchemaFactory.class) {
                if (null == UpdateDBFactory.UpdateDBSchemaFactory.__instance) {
                    UpdateDBFactory.UpdateDBSchemaFactory.__instance = new UpdateDBFactory.UpdateDBSchemaFactory();
                }

                return UpdateDBFactory.UpdateDBSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method getUpdateDB
                RequestSchema.JMethod method1 = this.addMethod("getUpdateDB",
                        "getDBUpdate",
                        "POST",
                        UpdateDBResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("Content-Type",
                        "HEADER",
                        String.class,
                        null,
                        "",
                        true);
                method1.addParam("body",
                        "PLAIN",
                        GetUpdateDBRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
