/*
  File generated by Magnet rest2mobile 1.1 - Jan 24, 2018 12:21:20 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.getUpdateDB.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getUpdateDB.model.beans.GetUpdateDBRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getUpdateDB.model.beans.UpdateDBResult;


public interface UpdateDB {

    /**
     * Generated from URL POST http://192.168.137.1:1234/getDBUpdate
     * POST getDBUpdate
     * @param contentType (original name : Content-Type) style:HEADER
     * @param body  style:PLAIN
     * @param listener
     * @return UpdateDBResult
     */
    Call<UpdateDBResult> getUpdateDB(
            String contentType,
            GetUpdateDBRequest body,
            StateChangedListener listener
    );


}
