/*
  File generated by Magnet rest2mobile 1.1 - Nov 14, 2017 10:42:38 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatId.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatId.model.beans.PosPatIdRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatId.model.beans.PosPatIdResult;

public class PostPatIdFactory extends ControllerFactory<PostPatId> {
    public PostPatIdFactory(MagnetMobileClient magnetClient) {
        super(PostPatId.class, PostPatIdFactory.PostPatIdSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PostPatId
    public static class PostPatIdSchemaFactory extends AbstractControllerSchemaFactory {
        private static PostPatIdFactory.PostPatIdSchemaFactory __instance;

        private PostPatIdSchemaFactory() {
        }

        static PostPatIdFactory.PostPatIdSchemaFactory getInstance() {
            synchronized (PostPatIdFactory.PostPatIdSchemaFactory.class) {
                if (null == PostPatIdFactory.PostPatIdSchemaFactory.__instance) {
                    PostPatIdFactory.PostPatIdSchemaFactory.__instance = new PostPatIdFactory.PostPatIdSchemaFactory();
                }

                return PostPatIdFactory.PostPatIdSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method posPatId
                RequestSchema.JMethod method1 = this.addMethod("posPatId",
                        "importMastersSP/GetPatientOperationInfo",
                        "POST",
                        PosPatIdResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("body",
                        "PLAIN",
                        PosPatIdRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
