/*
  File generated by Magnet rest2mobile 1.1 - Nov 14, 2017 10:42:38 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatId.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatId.model.beans.PosPatIdRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.posPatId.model.beans.PosPatIdResult;

public interface PostPatId {

    /**
     * Generated from URL POST http://192.168.137.143:1234/importMasters/postPatId
     * POST importMasters/postPatId
     * @param body  style:PLAIN
     * @param listener
     * @return PosPatIdResult
     */
    Call<PosPatIdResult> posPatId(
            PosPatIdRequest body,
            StateChangedListener listener
    );


}
