/*
  File generated by Magnet rest2mobile 1.1 - 8 Feb, 2018 11:48:07 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.updateDB.model.beans;


/**
 * Generated from json example
 {
 "Docid" : "DOCID/2017/05/81",
 "imei" : "",
 "mac" : ""
 }

 */

public class GetDBUpdateRequest {


    @com.google.gson.annotations.SerializedName("Docid")
    private String docid = null;


    private String imei = null;


    private String mac = null;

    public GetDBUpdateRequest() {
    }

    public final String getDocid() {
        return docid;
    }

    public final void setDocid(String docid) {
        this.docid = docid;
    }

    public final String getImei() {
        return imei;
    }

    public final void setImei(String imei) {
        this.imei = imei;
    }

    public final String getMac() {
        return mac;
    }

    public final void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * Builder for GetDBUpdateRequest
     **/
    public static class GetDBUpdateRequestBuilder {
        private final GetDBUpdateRequest toBuild = new GetDBUpdateRequest();

        public GetDBUpdateRequestBuilder() {
        }

        public final GetDBUpdateRequest build() {
            return toBuild;
        }

        public final GetDBUpdateRequestBuilder docid(String value) {
            toBuild.setDocid(value);
            return this;
        }

        public final GetDBUpdateRequestBuilder imei(String value) {
            toBuild.setImei(value);
            return this;
        }

        public final GetDBUpdateRequestBuilder mac(String value) {
            toBuild.setMac(value);
            return this;
        }
    }
}
