/*
  File generated by Magnet rest2mobile 1.1 - 8 Feb, 2018 11:48:07 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.updateDB.model.beans;


/**
 * Generated from json example
 {
 "Docid" : "DOCID/2017/05/81",
 "imei" : "",
 "mac" : ""
 }

 */

public class GetDBUpdateRequest {


    @com.google.gson.annotations.SerializedName("Docid")
    private String docid;


    private String imei;


    private String mac;

    public GetDBUpdateRequest() {
    }

    public final String getDocid() {
        return this.docid;
    }

    public final void setDocid(String docid) {
        this.docid = docid;
    }

    public final String getImei() {
        return this.imei;
    }

    public final void setImei(String imei) {
        this.imei = imei;
    }

    public final String getMac() {
        return this.mac;
    }

    public final void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * Builder for GetDBUpdateRequest
     **/
    public static class GetDBUpdateRequestBuilder {
        private final GetDBUpdateRequest toBuild = new GetDBUpdateRequest();

        public GetDBUpdateRequestBuilder() {
        }

        public final GetDBUpdateRequest build() {
            return this.toBuild;
        }

        public final GetDBUpdateRequest.GetDBUpdateRequestBuilder docid(String value) {
            this.toBuild.setDocid(value);
            return this;
        }

        public final GetDBUpdateRequest.GetDBUpdateRequestBuilder imei(String value) {
            this.toBuild.setImei(value);
            return this;
        }

        public final GetDBUpdateRequest.GetDBUpdateRequestBuilder mac(String value) {
            this.toBuild.setMac(value);
            return this;
        }
    }
}
