/*
  File generated by Magnet rest2mobile 1.1 - Nov 11, 2017 5:03:19 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.getPatientMapping.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getPatientMapping.model.beans.GetPatientMappingRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getPatientMapping.model.beans.PatientMappingResult;

public class PatientMappingFactory extends ControllerFactory<PatientMapping> {
    public PatientMappingFactory(MagnetMobileClient magnetClient) {
        super(PatientMapping.class, PatientMappingSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PatientMapping
    public static class PatientMappingSchemaFactory extends AbstractControllerSchemaFactory {
        private static PatientMappingSchemaFactory __instance = null;

        private PatientMappingSchemaFactory() {
        }

        static PatientMappingSchemaFactory getInstance() {
            synchronized (PatientMappingSchemaFactory.class) {
                if (null == __instance) {
                    __instance = new PatientMappingSchemaFactory();
                }

                return __instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != schema) {
                    return;
                }

                schema = new RequestSchema();
                schema.setRootPath("");


                //controller schema for controller method getPatientMapping
                JMethod method1 = addMethod("getPatientMapping",
                        "importMastersSP/importPatientMapping",
                        "POST",
                        PatientMappingResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("body",
                        "PLAIN",
                        GetPatientMappingRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
