/*
  File generated by Magnet rest2mobile 1.1 - Nov 11, 2017 5:03:19 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.getPatientMapping.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getPatientMapping.model.beans.GetPatientMappingRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getPatientMapping.model.beans.PatientMappingResult;

public class PatientMappingFactory extends ControllerFactory<PatientMapping> {
    public PatientMappingFactory(MagnetMobileClient magnetClient) {
        super(PatientMapping.class, PatientMappingFactory.PatientMappingSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller PatientMapping
    public static class PatientMappingSchemaFactory extends AbstractControllerSchemaFactory {
        private static PatientMappingFactory.PatientMappingSchemaFactory __instance;

        private PatientMappingSchemaFactory() {
        }

        static PatientMappingFactory.PatientMappingSchemaFactory getInstance() {
            synchronized (PatientMappingFactory.PatientMappingSchemaFactory.class) {
                if (null == PatientMappingFactory.PatientMappingSchemaFactory.__instance) {
                    PatientMappingFactory.PatientMappingSchemaFactory.__instance = new PatientMappingFactory.PatientMappingSchemaFactory();
                }

                return PatientMappingFactory.PatientMappingSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");


                //controller schema for controller method getPatientMapping
                RequestSchema.JMethod method1 = this.addMethod("getPatientMapping",
                        "importMastersSP/importPatientMapping",
                        "POST",
                        PatientMappingResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("body",
                        "PLAIN",
                        GetPatientMappingRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
