/*
  File generated by Magnet rest2mobile 1.1 - Nov 11, 2017 5:03:19 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.getPatientMapping.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getPatientMapping.model.beans.GetPatientMappingRequest;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.getPatientMapping.model.beans.PatientMappingResult;

public interface PatientMapping {

    /**
     * Generated from URL POST http://192.168.137.1:1234/importMasters/importPatientMapping
     * POST importMasters/importPatientMapping
     * @param body  style:PLAIN
     * @param listener
     * @return PatientMappingResult
     */
    Call<PatientMappingResult> getPatientMapping(
            GetPatientMappingRequest body,
            StateChangedListener listener
    );


}
