/*
  File generated by Magnet rest2mobile 1.1 - Nov 13, 2017 12:23:03 PM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.importREST_Services.postIsUpdateMax.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postIsUpdateMax.model.beans.IsUpdateMaxResult;
import kdmc_kumar.Webservices_NodeJSON.importREST_Services.postIsUpdateMax.model.beans.PostIsUpdateMaxRequest;

public interface PostIsUpdateMax {

    /**
     * Generated from URL POST http://192.168.137.143:1234/importMasters/postIsUpdateMax
     * POST importMasters/postIsUpdateMax
     * @param body  style:PLAIN
     * @param listener
     * @return IsUpdateMaxResult
     */
    Call<IsUpdateMaxResult> postIsUpdateMax(
            PostIsUpdateMaxRequest body,
            StateChangedListener listener
    );


}
