/*
  File generated by Magnet rest2mobile 1.1 - Nov 8, 2017 10:11:05 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.getMasters.model.beans;


/**
 * Generated from json example
 {
 "IsUpdateMax" : "0",
 "TableName" : "5"
 }

 */

public class GetMastersRequest {


    @com.google.gson.annotations.SerializedName("IsUpdateMax")
    private String isUpdateMax = null;


    @com.google.gson.annotations.SerializedName("TableName")
    private String tableName = null;

    public GetMastersRequest() {
    }

    public final String getIsUpdateMax() {
        return isUpdateMax;
    }

    public final void setIsUpdateMax(String isUpdateMax) {
        this.isUpdateMax = isUpdateMax;
    }

    public final String getTableName() {
        return tableName;
    }

    public final void setTableName(String tableName) {
        this.tableName = tableName;
    }


    /**
     * Builder for GetMastersRequest
     **/
    public static class GetMastersRequestBuilder {
        private final GetMastersRequest toBuild = new GetMastersRequest();

        public GetMastersRequestBuilder() {
        }

        public final GetMastersRequest build() {
            return toBuild;
        }

        public final GetMastersRequestBuilder isUpdateMax(String value) {
            toBuild.setIsUpdateMax(value);
            return this;
        }

        public final GetMastersRequestBuilder tableName(String value) {
            toBuild.setTableName(value);
            return this;
        }
    }
}
