/*
  File generated by Magnet rest2mobile 1.1 - Nov 8, 2017 10:11:05 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.getMasters.model.beans;


/**
 * Generated from json example
 {
 "Results" : ""
 }

 */

public class MastersResult {


    @com.google.gson.annotations.SerializedName("Results")
    private String results;

    public MastersResult() {
    }

    public final String getResults() {
        return this.results;
    }

    public void setResults(String results) {
        this.results = results;
    }

    /**
     * Builder for MastersResult
     **/
    public static class MastersResultBuilder {
        private final MastersResult toBuild = new MastersResult();

        public MastersResultBuilder() {
        }

        public final MastersResult build() {
            return this.toBuild;
        }

        public final MastersResult.MastersResultBuilder results(String value) {
            this.toBuild.setResults(value);
            return this;
        }
    }
}
