/*
  File generated by Magnet rest2mobile 1.1 - Nov 8, 2017 10:11:05 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.getMasters.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import kdmc_kumar.Webservices_NodeJSON.getMasters.model.beans.GetMastersRequest;
import kdmc_kumar.Webservices_NodeJSON.getMasters.model.beans.MastersResult;

public interface GetMaster {

    /**
     * Generated from URL POST http://192.168.137.89:1234/data/getMasterTables
     * POST data/getMasterTables
     * @param contentType (original name : Content-Type) style:HEADER
     * @param body  style:PLAIN
     * @param listener
     * @return MastersResult
     */
    Call<MastersResult> getMasters(
            String contentType,
            GetMastersRequest body,
            StateChangedListener listener
    );


}
