/*
  File generated by Magnet rest2mobile 1.1 - Nov 8, 2017 10:11:05 AM

  @see {@link http://developer.magnet.com}
 */

package kdmc_kumar.Webservices_NodeJSON.getMasters.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;

import java.util.Collections;

import kdmc_kumar.Core_Modules.BaseConfig;
import kdmc_kumar.Webservices_NodeJSON.getMasters.model.beans.GetMastersRequest;
import kdmc_kumar.Webservices_NodeJSON.getMasters.model.beans.MastersResult;

public class GetMasterFactory extends ControllerFactory<GetMaster> {
    public GetMasterFactory(MagnetMobileClient magnetClient) {
        super(GetMaster.class, GetMasterFactory.GetMasterSchemaFactory.getInstance().getSchema(), magnetClient);
    }

    // Schema factory for controller GetMaster
    public static class GetMasterSchemaFactory extends AbstractControllerSchemaFactory {
        private static GetMasterFactory.GetMasterSchemaFactory __instance;

        private GetMasterSchemaFactory() {
        }

        static GetMasterFactory.GetMasterSchemaFactory getInstance() {
            synchronized (GetMasterFactory.GetMasterSchemaFactory.class) {
                if (null == GetMasterFactory.GetMasterSchemaFactory.__instance) {
                    GetMasterFactory.GetMasterSchemaFactory.__instance = new GetMasterFactory.GetMasterSchemaFactory();
                }

                return GetMasterFactory.GetMasterSchemaFactory.__instance;
            }
        }

        protected final void initSchemaMaps() {
            synchronized (this) {
                if (null != this.schema) {
                    return;
                }

                this.schema = new RequestSchema();
                this.schema.setRootPath("");

                //controller schema for controller method getMasters
                RequestSchema.JMethod method1 = this.addMethod("getMasters",
                        "mastersSP/getMasterTables",
                        "POST",
                        MastersResult.class,
                        null,
                        Collections.singletonList("application/json"),
                        Collections.singletonList("application/json"));
                method1.setBaseUrl(BaseConfig.AppNodeIP);
                method1.addParam("Content-Type",
                        "HEADER",
                        String.class,
                        null,
                        "",
                        true);
                method1.addParam("body",
                        "PLAIN",
                        GetMastersRequest.class,
                        null,
                        "",
                        true);
            }
        }

    }

}
